# Charlie Eden

4/10/2026

In [1]:
# Setting working dir
import os
from pathlib import Path
p = os.getcwd() + "/../../"
os.chdir(p)
parent_dir = os.getcwd()

In [35]:
import numpy as np

config = {
    "years": np.arange(2019, 2025),
    "common_period": np.arange(2004, 2022),
    "imd_folder": f"{parent_dir}/../monsoon-benchmark_data/imd_rainfall_data/4p0",  # Ground truth rainfall data (4x4 degrees)
    "thresh_file": f"{parent_dir}/../monsoon-benchmark_data/imd_onset_threshold/mwset4x4.nc4",  # Threshold for the onset of the monsoon (4x4 degrees)
    "thres_file": f"{parent_dir}/../monsoon-benchmark_data/imd_onset_threshold/mwset4x4.nc4",  # Alternate naming convention
    "shpfile_path": f"{parent_dir}/../monsoon-benchmark_data/ind_map_shpfile/india_shapefile.shp",  # Shapefile of India
    "output_dir": f"{parent_dir}/examples/paper_figures/outputs",  # Directory to save data files,
    "mok": True,
    "day_bins_30": [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)],
    "day_bins_15": [(1, 5), (6, 10), (11, 15)],
    "mem_num": 51,
    "date_filter_year": 2024,
    "file_pattern": "{}.nc",
    "data_dir": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0",
}

# Paths to 4p0 model forecast data (.nc)
model_paths = {
    "IFS": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/IFS_S2S",  # IFS model
    "AIFS": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/AIFS",  # AIFS model
    "FuXi": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/FuXi",  # FuXi mdoel
    "Graphcast": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/GraphCast",  # Graphcast model
    "GenCast": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/GenCast",  # GenCast model
    "FuXi-S2S": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S",  # FuXi_S2S model
    "NGCM": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/NeuralGCM",  # NGCM model
}

prob_model_paths = {
        "FuXi S2S": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S",  # FuXi_S2S model
        "NGCM": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/NeuralGCM",  # NGCM model
        "IFS": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/IFS_S2S",  # AIFS model
        "GenCast": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/GenCast",  # GenCast model
    }

det_model_paths = {
        "AIFS": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/AIFS",
        "FuXi": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/FuXi",
        "Graphcast": f"{parent_dir}/../monsoon-benchmark_data/rainfall_4p0/GraphCast",  # Graphcast model
    }

In [36]:
from monsoonbench.metrics import (
    ProbabilisticOnsetMetrics,
    ClimatologyOnsetMetrics,
    DeterministicOnsetMetrics
)
from monsoonbench.visualization.compare_models import calculate_reliability_metrics
import xarray as xr

c = ClimatologyOnsetMetrics()
p = ProbabilisticOnsetMetrics()
d = DeterministicOnsetMetrics()

skills_15 = {}
skills_30 = {}
brier_15 = {}
brier_30 = {}
auc_15 = {}
auc_30 = {}
reliability_15 = {}

thresh_ds = xr.open_dataset(config["thresh_file"])
thresh_slice = thresh_ds["MWmean"]
clim_onset = c.compute_climatological_onset_dataset(
            config["imd_folder"], thresh_slice, years=None, mok=config["mok"]
        )

Processing 124 years: [1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Processing year 1901...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1901.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1901-06-02) as start date for onset detection
Year 1901: Found onset in 34/72 grid points (47.2%)

Processing year 1902...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1902.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1902-06-02) as start date for onset detection
Year 1902: Found onset in 36/72 grid points (50.0%)

Processing year 1903...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1903.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1903-06-02) as start date for onset detection
Year 1903: Found onset in 36/72 grid points (50.0%)

Processing year 1904...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1904.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1904-06-02) as start date for onset detection
Year 1904: Found onset in 35/72 grid points (48.6%)

Processing year 1905...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1905.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1905-06-02) as start date for onset detection
Year 1905: Found onset in 35/72 grid points (48.6%)

Processing year 1906...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1906.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1906-06-02) as start date for onset detection
Year 1906: Found onset in 36/72 grid points (50.0%)

Processing year 1907...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1907.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1907-06-02) as start date for onset detection
Year 1907: Found onset in 36/72 grid points (50.0%)

Processing year 1908...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1908.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1908-06-02) as start date for onset detection
Year 1908: Found onset in 36/72 grid points (50.0%)

Processing year 1909...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1909.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1909-06-02) as start date for onset detection
Year 1909: Found onset in 36/72 grid points (50.0%)

Processing year 1910...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1910.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1910-06-02) as start date for onset detection
Year 1910: Found onset in 36/72 grid points (50.0%)

Processing year 1911...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1911.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1911-06-02) as start date for onset detection
Year 1911: Found onset in 35/72 grid points (48.6%)

Processing year 1912...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1912.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1912-06-02) as start date for onset detection
Year 1912: Found onset in 36/72 grid points (50.0%)

Processing year 1913...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1913.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1913-06-02) as start date for onset detection
Year 1913: Found onset in 36/72 grid points (50.0%)

Processing year 1914...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1914.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1914-06-02) as start date for onset detection
Year 1914: Found onset in 36/72 grid points (50.0%)

Processing year 1915...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1915.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1915-06-02) as start date for onset detection
Year 1915: Found onset in 35/72 grid points (48.6%)

Processing year 1916...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1916.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1916-06-02) as start date for onset detection
Year 1916: Found onset in 36/72 grid points (50.0%)

Processing year 1917...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1917.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1917-06-02) as start date for onset detection
Year 1917: Found onset in 36/72 grid points (50.0%)

Processing year 1918...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1918.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1918-06-02) as start date for onset detection
Year 1918: Found onset in 33/72 grid points (45.8%)

Processing year 1919...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1919.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1919-06-02) as start date for onset detection
Year 1919: Found onset in 36/72 grid points (50.0%)

Processing year 1920...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1920.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1920-06-02) as start date for onset detection
Year 1920: Found onset in 35/72 grid points (48.6%)

Processing year 1921...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1921.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1921-06-02) as start date for onset detection
Year 1921: Found onset in 36/72 grid points (50.0%)

Processing year 1922...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1922.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1922-06-02) as start date for onset detection
Year 1922: Found onset in 36/72 grid points (50.0%)

Processing year 1923...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1923.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1923-06-02) as start date for onset detection
Year 1923: Found onset in 36/72 grid points (50.0%)

Processing year 1924...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1924.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1924-06-02) as start date for onset detection
Year 1924: Found onset in 36/72 grid points (50.0%)

Processing year 1925...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1925.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1925-06-02) as start date for onset detection
Year 1925: Found onset in 36/72 grid points (50.0%)

Processing year 1926...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1926.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1926-06-02) as start date for onset detection
Year 1926: Found onset in 36/72 grid points (50.0%)

Processing year 1927...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1927.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1927-06-02) as start date for onset detection
Year 1927: Found onset in 36/72 grid points (50.0%)

Processing year 1928...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1928.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1928-06-02) as start date for onset detection
Year 1928: Found onset in 35/72 grid points (48.6%)

Processing year 1929...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1929.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1929-06-02) as start date for onset detection
Year 1929: Found onset in 36/72 grid points (50.0%)

Processing year 1930...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1930.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1930-06-02) as start date for onset detection
Year 1930: Found onset in 36/72 grid points (50.0%)

Processing year 1931...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1931.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1931-06-02) as start date for onset detection
Year 1931: Found onset in 36/72 grid points (50.0%)

Processing year 1932...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1932.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1932-06-02) as start date for onset detection
Year 1932: Found onset in 36/72 grid points (50.0%)

Processing year 1933...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1933.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1933-06-02) as start date for onset detection
Year 1933: Found onset in 36/72 grid points (50.0%)

Processing year 1934...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1934.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1934-06-02) as start date for onset detection
Year 1934: Found onset in 36/72 grid points (50.0%)

Processing year 1935...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1935.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1935-06-02) as start date for onset detection
Year 1935: Found onset in 36/72 grid points (50.0%)

Processing year 1936...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1936.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1936-06-02) as start date for onset detection
Year 1936: Found onset in 36/72 grid points (50.0%)

Processing year 1937...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1937.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1937-06-02) as start date for onset detection
Year 1937: Found onset in 36/72 grid points (50.0%)

Processing year 1938...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1938.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1938-06-02) as start date for onset detection
Year 1938: Found onset in 36/72 grid points (50.0%)

Processing year 1939...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1939.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1939-06-02) as start date for onset detection
Year 1939: Found onset in 35/72 grid points (48.6%)

Processing year 1940...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1940.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1940-06-02) as start date for onset detection
Year 1940: Found onset in 36/72 grid points (50.0%)

Processing year 1941...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1941.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1941-06-02) as start date for onset detection
Year 1941: Found onset in 36/72 grid points (50.0%)

Processing year 1942...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1942.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1942-06-02) as start date for onset detection
Year 1942: Found onset in 36/72 grid points (50.0%)

Processing year 1943...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1943.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1943-06-02) as start date for onset detection
Year 1943: Found onset in 36/72 grid points (50.0%)

Processing year 1944...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1944.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1944-06-02) as start date for onset detection
Year 1944: Found onset in 36/72 grid points (50.0%)

Processing year 1945...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1945.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1945-06-02) as start date for onset detection
Year 1945: Found onset in 36/72 grid points (50.0%)

Processing year 1946...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1946.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1946-06-02) as start date for onset detection
Year 1946: Found onset in 35/72 grid points (48.6%)

Processing year 1947...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1947.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1947-06-02) as start date for onset detection
Year 1947: Found onset in 36/72 grid points (50.0%)

Processing year 1948...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1948.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1948-06-02) as start date for onset detection
Year 1948: Found onset in 36/72 grid points (50.0%)

Processing year 1949...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1949.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1949-06-02) as start date for onset detection
Year 1949: Found onset in 36/72 grid points (50.0%)

Processing year 1950...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1950.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1950-06-02) as start date for onset detection
Year 1950: Found onset in 35/72 grid points (48.6%)

Processing year 1951...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1951.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1951-06-02) as start date for onset detection
Year 1951: Found onset in 36/72 grid points (50.0%)

Processing year 1952...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1952.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1952-06-02) as start date for onset detection
Year 1952: Found onset in 36/72 grid points (50.0%)

Processing year 1953...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1953.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1953-06-02) as start date for onset detection
Year 1953: Found onset in 36/72 grid points (50.0%)

Processing year 1954...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1954.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1954-06-02) as start date for onset detection
Year 1954: Found onset in 36/72 grid points (50.0%)

Processing year 1955...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1955.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1955-06-02) as start date for onset detection
Year 1955: Found onset in 36/72 grid points (50.0%)

Processing year 1956...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1956.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1956-06-02) as start date for onset detection
Year 1956: Found onset in 36/72 grid points (50.0%)

Processing year 1957...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1957.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1957-06-02) as start date for onset detection
Year 1957: Found onset in 36/72 grid points (50.0%)

Processing year 1958...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1958.nc
Renamed dimensions: {'TIME': 'time'}

### Fig 2 -- Probabilistic Scores

In [5]:
# 15 day
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    print("\n")
    print(f"Processing {model_name}")
    print("="*50)
    forecast_df = p.multi_year_forecast_obs_pairs(
            range(2019, 2024),
            model_forecast_dir=model_paths[model_name],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            mem_num=51,
            max_forecast_day=15,
            day_bins=config["day_bins_15"],
            date_filter_year=config["date_filter_year"],
        )
    
    climatology_obs_df = c.multi_year_climatological_forecast_obs_pairs(
            clim_onset,
            config["years"],
            config["day_bins_15"],
            config["mem_num"],
            model_paths[model_name],
            date_filter_year=config["date_filter_year"],
            file_pattern=config["file_pattern"],
            max_forecast_day=15,
            mok=config["mok"],
        )
    
    brier_forecast = p.calculate_brier_score(forecast_df)
    rps_forecast = p.calculate_rps(forecast_df)
    auc_forecast = p.calculate_auc(forecast_df)

    brier_climatology = c.calculate_brier_score_climatology(climatology_obs_df)
    rps_climatology = p.calculate_rps(climatology_obs_df)
    auc_climatology = c.calculate_auc_climatology(climatology_obs_df)


    skill_results = p.calculate_skill_scores(
            brier_forecast, rps_forecast, brier_climatology, rps_climatology
        )
    
    reliability_metrics = calculate_reliability_metrics(forecast_df)

    skills_15[model_name] = skill_results
    reliability_15[model_name] = reliability_metrics
    auc_15[model_name] = auc_forecast
    brier_15[model_name] = brier_forecast

Processing IFS
==================================================
Processing years: range(2019, 2024)

Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2019
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2019.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2019-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2019-05-02
Processing init time 6/26: 2019-05-20
Processing init time 11/26: 2019-06-06
Processing init time 16/26: 2019-06-24
Processing init time 21/26: 2019-07-11
Processing init time 26/26: 2019-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1210
Valid forecasts processed: 1650
Generated 1650 member-forecast combinations
Found onset in 435 cases
Onset rate: 0.264
✓ All init_time-lat-lon-member combinations are unique
Found onset in 435 member cases
Creating forecast-observation pairs...
Processing 150 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 600 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 275

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            150  0.736          0.727
Days 1-5                150  0.076          0.080
Days 11-15              150  0.090          0.093
Days 6-10               150  0.097          0.100
Year 2019 completed: 600 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2020-05-02
Processing init time 6/26: 2020-05-20
Processing init time 11/26: 2020-06-06
Processing init time 16/26: 2020-06-24
Processing init time 21/26: 2020-07-11
Processing init time 26/26: 2020-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1474
Valid forecasts processed: 1386
Generated 1386 member-forecast combinations
Found onset in 571 cases
Onset rate: 0.412
✓ All init_time-lat-lon-member combinations are unique
Found onset in 571 member cases
Creating forecast-observation pairs...
Processing 126 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 504 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 253

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            126  0.588          0.651
Days 1-5                126  0.167          0.119
Days 11-15              126  0.119          0.127
Days 6-10               126  0.126          0.103
Year 2020 completed: 504 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2021-05-02
Processing init time 6/26: 2021-05-20
Processing init time 11/26: 2021-06-06
Processing init time 16/26: 2021-06-24
Processing init time 21/26: 2021-07-11
Processing init time 26/26: 2021-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1529
Valid forecasts processed: 1331
Generated 1331 member-forecast combinations
Found onset in 422 cases
Onset rate: 0.317
✓ All init_time-lat-lon-member combinations are unique
Found onset in 422 member cases
Creating forecast-observation pairs...
Processing 121 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 484 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 215

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            121  0.683          0.661
Days 1-5                121  0.107          0.107
Days 11-15              121  0.101          0.107
Days 6-10               121  0.108          0.124
Year 2021 completed: 484 forecast-observation pairs

==================================================
Processing year 2022
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2022.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2022-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2022-05-02
Processing init time 6/26: 2022-05-20
Processing init time 11/26: 2022-06-06
Processing init time 16/26: 2022-06-24
Processing init time 21/26: 2022-07-11
Processing init time 26/26: 2022-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1320
Valid forecasts processed: 1540
Generated 1540 member-forecast combinations
Found onset in 455 cases
Onset rate: 0.295
✓ All init_time-lat-lon-member combinations are unique
Found onset in 455 member cases
Creating forecast-observation pairs...
Processing 140 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 560 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 247

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            140  0.705          0.700
Days 1-5                140  0.102          0.114
Days 11-15              140  0.108          0.093
Days 6-10               140  0.085          0.093
Year 2022 completed: 560 forecast-observation pairs

==================================================
Processing year 2023
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2023.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2023-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2023-05-02
Processing init time 6/26: 2023-05-20
Processing init time 11/26: 2023-06-06
Processing init time 16/26: 2023-06-24
Processing init time 21/26: 2023-07-11
Processing init time 26/26: 2023-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1331
Valid forecasts processed: 1529
Generated 1529 member-forecast combinations
Found onset in 492 cases
Onset rate: 0.322
✓ All init_time-lat-lon-member combinations are unique
Found onset in 492 member cases
Creating forecast-observation pairs...
Processing 139 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 556 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 258

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            139  0.678          0.683
Days 1-5                139  0.102          0.108
Days 11-15              139  0.102          0.115
Days 6-10               139  0.118          0.094
Year 2023 completed: 556 forecast-observation pairs

==================================================
Combining all years
==================================================

Final Summary Statistics:
Years processed: range(2019, 2024)
Using 4-degree CMZ polygon coordinates

==================================================
Processing target year 2019
==================================================
Creating climatological forecasts for target year 2019
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 26 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 750 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 457
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                     150  0.666          0.727
Before initialization            150  0.109          0.000
Days 1-5                         150  0.064          0.080
Days 11-15                       150  0.086          0.093
Days 6-10                        150  0.074          0.100

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        82.533                  123.907
Before initialization               13.513                  123.907
Days 1-5                             7.987                  123.907
Days 11-15                          10.667                  123.907
Days 6-10                            9.207                  123.907
Target year 2019 completed: 750 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 26 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 630 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 350
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                     126  0.731          0.651
Before initialization            126  0.069          0.000
Days 1-5                         126  0.048          0.119
Days 11-15                       126  0.082          0.127
Days 6-10                        126  0.069          0.103

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        90.611                  123.921
Before initialization                8.595                  123.921
Days 1-5                             5.937                  123.921
Days 11-15                          10.222                  123.921
Days 6-10                            8.556                  123.921
Target year 2020 completed: 630 pairs

==================================================
Processing target year 2021
==================================================
Creating climatological forecasts for target year 2021

Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2022.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2023.nc

Generated 390 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 228
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                      78  0.677          0.731
Before initialization             78  0.108          0.000
Days 1-5                          78  0.065          0.077
Days 11-15                        78  0.082          0.103
Days 6-10                         78  0.067          0.090

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        83.897                   123.91
Before initialization               13.385                   123.91
Days 1-5                             8.115                   123.91
Days 11-15                          10.218                   123.91
Days 6-10                            8.295                   123.91
Target year 2019 completed: 390 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 325 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 175
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                      65  0.754          0.692
Before initialization             65  0.058          0.000
Days 1-5                          65  0.048          0.123
Days 11-15                        65  0.076          0.123
Days 6-10                         65  0.064          0.062

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        93.385                  123.923
Before initialization                7.231                  123.923
Days 1-5                             5.954                  123.923
Days 11-15                           9.415                  123.923
Days 6-10                            7.938                  123.923
Target year 2020 completed: 325 pairs

==================================================
Processing target year 2021
==================================================
Creating climatological forecasts for target year 2021
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 320 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 160
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                      64  0.786          0.672
Before initialization             64  0.048          0.000
Days 1-5                          64  0.042          0.109
Days 11-15                        64  0.076          0.094
Days 6-10                         64  0.047          0.125

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        97.406                  123.922
Before initialization                5.984                  123.922
Days 1-5                             5.266                  123.922
Days 11-15                           9.438                  123.922
Days 6-10                            5.828                  123.922
Target year 2021 completed: 320 pairs

==================================================
Processing target year 2022
==================================================
Error processing target year 2022: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2022.nc

==================================================
Processing target year 2023
==================================================
Error processing target year 2023: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2023.nc

==================================================
Processing target year 2024
==================================================
Error processing target year 2024: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2024.nc

==================================================
CLIMATOLOGICAL FORECAST SUMMARY
==================================================
Target years processed: [2019 2020 2021 2022 2023 2024]
Total forecast-observation pairs: 1035
Probability range: 0.000 - 1.000
Overall observed onset rate: 0.200
Brier Score: 0.0864
Fair Brier Score: 0.0859
RPS: 0.2608
Fair RPS: 0.2596
Number of forecasts: 207
Calculating Brier Score excluding 'Before initialization' bin
Original samples: 1035, After filtering: 828
Brier Score (excluding 'Before initialization'): 0.0826
Fair Brier Score (excluding 'Before initialization'): 0.0821
Bins included in calculation: ['After day 15', 'Days 1-5', 'Days 11-15', 'Days 6-10']
RPS: 0.2781
Fair RPS: 0.2759
Number of forecasts: 207
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): -0.0455
Fair RPS Skill Score (1-15 day): 0.0592

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: ['After day 15']

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.2086
  Days 6-10: Fair BSS = 0.0694
  Days 11-15: Fair BSS = -0.1556

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         -0.0455            0.2086       0.0694       -0.1556
Fair RPS Skill Score           0.0592             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0859
Climatology Fair Brier Score : 0.0821
Fair Brier Skill Score: -0.0455

Forecast Fair RPS : 0.2596
Climatology Fair RPS : 0.2759
Fair RPS Skill Score: 0.0592

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0619
    Climatology: 0.0783
    Skill Score: 0.2086
  Days 6-10:
    Forecast: 0.0679
    Climatology: 0.0730
    Skill Score: 0.0694
  Days 11-15:
    Forecast: 0.0981
    Climatology: 0.0849
    Skill Score: -0.1556


Processing NGCM
==================================================
Processing years: range(2019, 2024)
Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2019
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2019.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2019-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2019-05-02
Processing init time 6/26: 2019-05-20
Processing init time 11/26: 2019-06-06
Processing init time 16/26: 2019-06-24
Processing init time 21/26: 2019-07-11
Processing init time 26/26: 2019-07-29

Processing Summary:
Total potential forecasts: 13260
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 5610
Valid forecasts processed: 7650
Generated 7650 member-forecast combinations
Found onset in 1969 cases
Onset rate: 0.257
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1969 member cases
Creating forecast-observation pairs...
Processing 150 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 600 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 343

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            150  0.743          0.727
Days 1-5                150  0.094          0.080
Days 11-15              150  0.082          0.093
Days 6-10               150  0.082          0.100
Year 2019 completed: 600 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2020-05-02
Processing init time 6/26: 2020-05-20
Processing init time 11/26: 2020-06-06
Processing init time 16/26: 2020-06-24
Processing init time 21/26: 2020-07-11
Processing init time 26/26: 2020-07-29

Processing Summary:
Total potential forecasts: 13260
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 6834
Valid forecasts processed: 6426
Generated 6426 member-forecast combinations
Found onset in 2601 cases
Onset rate: 0.405
✓ All init_time-lat-lon-member combinations are unique
Found onset in 2601 member cases
Creating forecast-observation pairs...
Processing 126 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 504 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 282

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            126  0.595          0.651
Days 1-5                126  0.188          0.119
Days 11-15              126  0.085          0.127
Days 6-10               126  0.132          0.103
Year 2020 completed: 504 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2021-05-02
Processing init time 6/26: 2021-05-20
Processing init time 11/26: 2021-06-06
Processing init time 16/26: 2021-06-24
Processing init time 21/26: 2021-07-11
Processing init time 26/26: 2021-07-29

Processing Summary:
Total potential forecasts: 13260
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 7089
Valid forecasts processed: 6171
Generated 6171 member-forecast combinations
Found onset in 1597 cases
Onset rate: 0.259
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1597 member cases
Creating forecast-observation pairs...
Processing 121 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 484 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 261

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15            121  0.741          0.661
Days 1-5                121  0.100          0.107
Days 11-15              121  0.082          0.107
Days 6-10               121  0.077          0.124
Year 2021 completed: 484 forecast-observation pairs

==================================================
Processing year 2022
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2022.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2022-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...

In [6]:
# 30 day
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    print("\n")
    print(f"Processing {model_name}")
    print("="*50)
    forecast_df = p.multi_year_forecast_obs_pairs(
            range(2019, 2024),
            model_forecast_dir=model_paths[model_name],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            mem_num=51,
            max_forecast_day=30,
            day_bins=config["day_bins_30"],
            date_filter_year=config["date_filter_year"],
        )
    
    climatology_obs_df = c.multi_year_climatological_forecast_obs_pairs(
            clim_onset,
            config["years"],
            config["day_bins_30"],
            config["mem_num"],
            model_paths[model_name],
            date_filter_year=config["date_filter_year"],
            file_pattern=config["file_pattern"],
            max_forecast_day=30,
            mok=config["mok"],
        )
    
    brier_forecast = p.calculate_brier_score(forecast_df)
    rps_forecast = p.calculate_rps(forecast_df)
    auc_forecast = p.calculate_auc(forecast_df)

    brier_climatology = c.calculate_brier_score_climatology(climatology_obs_df)
    rps_climatology = p.calculate_rps(climatology_obs_df)
    auc_climatology = c.calculate_auc_climatology(climatology_obs_df)


    skill_results = p.calculate_skill_scores(
            brier_forecast, rps_forecast, brier_climatology, rps_climatology
        )
    
    skills_30[model_name] = skill_results  
    auc_30[model_name] = auc_forecast
    brier_30[model_name] = brier_forecast

Processing IFS
==================================================
Processing years: range(2019, 2024)
Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2019
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2019.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2019-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2019-05-02
Processing init time 6/26: 2019-05-20
Processing init time 11/26: 2019-06-06
Processing init time 16/26: 2019-06-24
Processing init time 21/26: 2019-07-11
Processing init time 26/26: 2019-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1210
Valid forecasts processed: 1650
Generated 1650 member-forecast combinations
Found onset in 884 cases
Onset rate: 0.536
✓ All init_time-lat-lon-member combinations are unique
Found onset in 884 member cases
Creating forecast-observation pairs...
Processing 150 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 1050 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 466

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            150  0.464          0.447
Days 1-5                150  0.076          0.080
Days 11-15              150  0.090          0.093
Days 16-20              150  0.084          0.087
Days 21-25              150  0.092          0.113
Days 26-30              150  0.096          0.080
Days 6-10               150  0.097          0.100
Year 2019 completed: 1050 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2020-05-02
Processing init time 6/26: 2020-05-20
Processing init time 11/26: 2020-06-06
Processing init time 16/26: 2020-06-24
Processing init time 21/26: 2020-07-11
Processing init time 26/26: 2020-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1474
Valid forecasts processed: 1386
Generated 1386 member-forecast combinations
Found onset in 916 cases
Onset rate: 0.661
✓ All init_time-lat-lon-member combinations are unique
Found onset in 916 member cases
Creating forecast-observation pairs...
Processing 126 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 882 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 393

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            126  0.339          0.317
Days 1-5                126  0.167          0.119
Days 11-15              126  0.119          0.127
Days 16-20              126  0.073          0.103
Days 21-25              126  0.067          0.103
Days 26-30              126  0.109          0.127
Days 6-10               126  0.126          0.103
Year 2020 completed: 882 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2021-05-02
Processing init time 6/26: 2021-05-20
Processing init time 11/26: 2021-06-06
Processing init time 16/26: 2021-06-24
Processing init time 21/26: 2021-07-11
Processing init time 26/26: 2021-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1529
Valid forecasts processed: 1331
Generated 1331 member-forecast combinations
Found onset in 810 cases
Onset rate: 0.609
✓ All init_time-lat-lon-member combinations are unique
Found onset in 810 member cases
Creating forecast-observation pairs...
Processing 121 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 847 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 376

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            121  0.391          0.298
Days 1-5                121  0.107          0.107
Days 11-15              121  0.101          0.107
Days 16-20              121  0.107          0.132
Days 21-25              121  0.089          0.116
Days 26-30              121  0.095          0.116
Days 6-10               121  0.108          0.124
Year 2021 completed: 847 forecast-observation pairs

==================================================
Processing year 2022
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2022.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2022-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2022-05-02
Processing init time 6/26: 2022-05-20
Processing init time 11/26: 2022-06-06
Processing init time 16/26: 2022-06-24
Processing init time 21/26: 2022-07-11
Processing init time 26/26: 2022-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1320
Valid forecasts processed: 1540
Generated 1540 member-forecast combinations
Found onset in 1079 cases
Onset rate: 0.701
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1079 member cases
Creating forecast-observation pairs...
Processing 140 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 980 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 443

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            140  0.299          0.379
Days 1-5                140  0.102          0.114
Days 11-15              140  0.108          0.093
Days 16-20              140  0.153          0.114
Days 21-25              140  0.134          0.086
Days 26-30              140  0.118          0.121
Days 6-10               140  0.085          0.093
Year 2022 completed: 980 forecast-observation pairs

==================================================
Processing year 2023
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2023.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2023-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2023-05-02
Processing init time 6/26: 2023-05-20
Processing init time 11/26: 2023-06-06
Processing init time 16/26: 2023-06-24
Processing init time 21/26: 2023-07-11
Processing init time 26/26: 2023-07-29

Processing Summary:
Total potential forecasts: 2860
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 1331
Valid forecasts processed: 1529
Generated 1529 member-forecast combinations
Found onset in 878 cases
Onset rate: 0.574
✓ All init_time-lat-lon-member combinations are unique
Found onset in 878 member cases
Creating forecast-observation pairs...
Processing 139 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 973 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 424

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            139  0.426          0.381
Days 1-5                139  0.102          0.108
Days 11-15              139  0.102          0.115
Days 16-20              139  0.076          0.086
Days 21-25              139  0.093          0.115
Days 26-30              139  0.084          0.101
Days 6-10               139  0.118          0.094
Year 2023 completed: 973 forecast-observation pairs

==================================================
Combining all years
==================================================

Final Summary Statistics:
Years processed: range(2019, 2024)
Using 4-degree CMZ polygon coordinates

==================================================
Processing target year 2019
==================================================
Creating climatological forecasts for target year 2019
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 26 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 1200 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 799
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                     150  0.394          0.447
Before initialization            150  0.109          0.000
Days 1-5                         150  0.064          0.080
Days 11-15                       150  0.086          0.093
Days 16-20                       150  0.087          0.087
Days 21-25                       150  0.092          0.113
Days 26-30                       150  0.093          0.080
Days 6-10                        150  0.074          0.100

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        48.833                  123.907
Before initialization               13.513                  123.907
Days 1-5                             7.987                  123.907
Days 11-15                          10.667                  123.907
Days 16-20                          10.807                  123.907
Days 21-25                          11.340                  123.907
Days 26-30                          11.553                  123.907
Days 6-10                            9.207                  123.907
Target year 2019 completed: 1200 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 26 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 1008 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 650
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean

Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2022.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2023.nc

Generated 624 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 402
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      78  0.417          0.462
Before initialization             78  0.108          0.000
Days 1-5                          78  0.065          0.077
Days 11-15                        78  0.082          0.103
Days 16-20                        78  0.088          0.077
Days 21-25                        78  0.086          0.115
Days 26-30                        78  0.086          0.077
Days 6-10                         78  0.067          0.090

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        51.667                   123.91
Before initialization               13.385                   123.91
Days 1-5                             8.115                   123.91
Days 11-15                          10.218                   123.91
Days 16-20                          10.885                   123.91
Days 21-25                          10.667                   123.91
Days 26-30                          10.679                   123.91
Days 6-10                            8.295                   123.91
Target year 2019 completed: 624 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 520 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 322
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      65  0.468          0.369
Before initialization             65  0.058          0.000
Days 1-5                          65  0.048          0.123
Days 11-15                        65  0.076          0.123
Days 16-20                        65  0.092          0.138
Days 21-25                        65  0.101          0.077
Days 26-30                        65  0.093          0.108
Days 6-10                         65  0.064          0.062

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        57.969                  123.923
Before initialization                7.231                  123.923
Days 1-5                             5.954                  123.923
Days 11-15                           9.415                  123.923
Days 16-20                          11.431                  123.923
Days 21-25                          12.492                  123.923
Days 26-30                          11.492                  123.923
Days 6-10                            7.938                  123.923
Target year 2020 completed: 520 pairs

==================================================
Processing target year 2021
==================================================
Creating climatological forecasts for target year 2021
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 512 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 309
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      64  0.498          0.328
Before initialization             64  0.048          0.000
Days 1-5                          64  0.042          0.109
Days 11-15                        64  0.076          0.094
Days 16-20                        64  0.092          0.125
Days 21-25                        64  0.096          0.125
Days 26-30                        64  0.101          0.094
Days 6-10                         64  0.047          0.125

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        61.641                  123.922
Before initialization                5.984                  123.922
Days 1-5                             5.266                  123.922
Days 11-15                           9.438                  123.922
Days 16-20                          11.391                  123.922
Days 21-25                          11.859                  123.922
Days 26-30                          12.516                  123.922
Days 6-10                            5.828                  123.922
Target year 2021 completed: 512 pairs

==================================================
Processing target year 2022
==================================================
Error processing target year 2022: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2022.nc

==================================================
Processing target year 2023
==================================================
Error processing target year 2023: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2023.nc

==================================================
Processing target year 2024
==================================================
Error processing target year 2024: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/FuXi_S2S/2024.nc

==================================================
CLIMATOLOGICAL FORECAST SUMMARY
==================================================
Target years processed: [2019 2020 2021 2022 2023 2024]
Total forecast-observation pairs: 1656
Probability range: 0.000 - 1.000
Overall observed onset rate: 0.125
Brier Score: 0.0935
Fair Brier Score: 0.0925
RPS: 0.6759
Fair RPS: 0.6706
Number of forecasts: 207
Calculating Brier Score excluding 'Before initialization' bin
Original samples: 1656, After filtering: 1449
Brier Score (excluding 'Before initialization'): 0.0853
Fair Brier Score (excluding 'Before initialization'): 0.0847
Bins included in calculation: ['After day 30', 'Days 1-5', 'Days 11-15', 'Days 16-20', 'Days 21-25', 'Days 26-30', 'Days 6-10']
RPS: 0.6050
Fair RPS: 0.6001
Number of forecasts: 207
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): -0.0929
Fair RPS Skill Score (1-15 day): -0.1174

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15', 'Days 16-20', 'Days 21-25', 'Days 26-30']
Excluded bins: ['After day 30']

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.2086
  Days 6-10: Fair BSS = 0.0694
  Days 11-15: Fair BSS = -0.1556
  Days 16-20: Fair BSS = -0.0816
  Days 21-25: Fair BSS = -0.2725
  Days 26-30: Fair BSS = -0.0185

========================================================================================================================
SKILL SCORE SUMMARY TABLE
========================================================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15        16-20        21-25        26-30
------------------------------------------------------------------------------------------------------------------------
Fair Brier Skill Score         -0.0929            0.2086       0.0694       -0.1556      -0.0816      -0.2725      -0.0185
Fair RPS Skill Score           -0.1174            N/A          N/A          N/A          N/A          N/A          N/A
------------------------------------------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0925
Climatology Fair Brier Score : 0.0847
Fair Brier Skill Score: -0.0929

Forecast Fair RPS : 0.6706
Climatology Fair RPS : 0.6001
Fair RPS Skill Score: -0.1174

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0619
    Climatology: 0.0783
    Skill Score: 0.2086
  Days 6-10:
    Forecast: 0.0679
    Climatology: 0.0730
    Skill Score: 0.0694
  Days 11-15:
    Forecast: 0.0981
    Climatology: 0.0849
    Skill Score: -0.1556
  Days 16-20:
    Forecast: 0.0948
    Climatology: 0.0877
    Skill Score: -0.0816
  Days 21-25:
    Forecast: 0.1108
    Climatology: 0.0871
    Skill Score: -0.2725
  Days 26-30:
    Forecast: 0.0781
    Climatology: 0.0767
    Skill Score: -0.0185


Processing NGCM
==================================================
Processing years: range(2019, 2024)
Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2019
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2019.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2019-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2019-05-02
Processing init time 6/26: 2019-05-20
Processing init time 11/26: 2019-06-06
Processing init time 16/26: 2019-06-24
Processing init time 21/26: 2019-07-11
Processing init time 26/26: 2019-07-29

Processing Summary:
Total potential forecasts: 13260
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 5610
Valid forecasts processed: 7650
Generated 7650 member-forecast combinations
Found onset in 4729 cases
Onset rate: 0.618
✓ All init_time-lat-lon-member combinations are unique
Found onset in 4729 member cases
Creating forecast-observation pairs...
Processing 150 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 1050 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 667

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            150  0.382          0.447
Days 1-5                150  0.094          0.080
Days 11-15              150  0.082          0.093
Days 16-20              150  0.107          0.087
Days 21-25              150  0.135          0.113
Days 26-30              150  0.119          0.080
Days 6-10               150  0.082          0.100
Year 2019 completed: 1050 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/26: 2020-05-02
Processing init time 6/26: 2020-05-20
Processing init time 11/26: 2020-06-06
Processing init time 16/26: 2020-06-24
Processing init time 21/26: 2020-07-11
Processing init time 26/26: 2020-07-29

Processing Summary:
Total potential forecasts: 13260
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 6834
Valid forecasts processed: 6426
Generated 6426 member-forecast combinations
Found onset in 3975 cases
Onset rate: 0.619
✓ All init_time-lat-lon-member combinations are unique
Found onset in 3975 member cases
Creating forecast-observation pairs...
Processing 126 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 882 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 499

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30            126  0.381          0.317
Days 1-5                126  0.188          0.119
Days 11-15              126  0.085          0.127
Days 16-20              126  0.074          0.103
Days 21-25              126  0.070          0.103
Days 26-30              126  0.070          0.127
Days 6-10               126  0.132          0.103
Year 2020 completed: 882 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 26 init times x 10 unique locations x 51 members...

In [9]:
import pandas as pd
rows = []
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    row = {}
    row["model_label"] = model_name.lower()
    row["horizon"] = 15

    row["fair_brier_skill_d1_5"] = skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 1-5"]
    row["fair_brier_skill_d6_10"] = skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 6-10"]
    row["fair_brier_skill_d11_15"] = skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 11-15"]
    row["fair_brier_skill_d16_20"] = None
    row["fair_brier_skill_d21_25"] = None
    row["fair_brier_skill_d26_30"] = None

    row["fair_brier_d1_5"] = brier_15[model_name]["bin_fair_brier_scores"]["Days 1-5"]
    row["fair_brier_d6_10"] = brier_15[model_name]["bin_fair_brier_scores"]["Days 6-10"]
    row["fair_brier_d11_15"] = brier_15[model_name]["bin_fair_brier_scores"]["Days 11-15"]
    row["fair_brier_d16_20"] = None
    row["fair_brier_d21_25"] = None
    row["fair_brier_d26_30"] = None

    row["auc_d1_5"] = auc_15[model_name]["bin_auc_scores"]["Days 1-5"]
    row["auc_d6_10"] = auc_15[model_name]["bin_auc_scores"]["Days 6-10"]
    row["auc_d11_15"] = auc_15[model_name]["bin_auc_scores"]["Days 11-15"]
    row["auc_d16_20"] = None
    row["auc_d21_25"] = None
    row["auc_d26_30"] = None
    row["auc_later"] = auc_15[model_name]["bin_auc_scores"]["After day 15"]

    rows.append(row)


    row = {}
    row["model_label"] = model_name.lower()
    row["horizon"] = 30

    row["fair_brier_skill_d1_5"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 1-5"]
    row["fair_brier_skill_d6_10"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 6-10"]
    row["fair_brier_skill_d11_15"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 11-15"]
    row["fair_brier_skill_d16_20"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 16-20"]
    row["fair_brier_skill_d21_25"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 21-25"]
    row["fair_brier_skill_d26_30"] = skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 26-30"]

    row["fair_brier_d1_5"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 1-5"]
    row["fair_brier_d6_10"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 6-10"]
    row["fair_brier_d11_15"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 11-15"]
    row["fair_brier_d16_20"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 16-20"]
    row["fair_brier_d21_25"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 21-25"]
    row["fair_brier_d26_30"] = brier_30[model_name]["bin_fair_brier_scores"]["Days 26-30"]

    row["auc_d1_5"] = auc_30[model_name]["bin_auc_scores"]["Days 1-5"]
    row["auc_d6_10"] = auc_30[model_name]["bin_auc_scores"]["Days 6-10"]
    row["auc_d11_15"] = auc_30[model_name]["bin_auc_scores"]["Days 11-15"]
    row["auc_d16_20"] = auc_30[model_name]["bin_auc_scores"]["Days 16-20"]
    row["auc_d21_25"] = auc_30[model_name]["bin_auc_scores"]["Days 21-25"]
    row["auc_d26_30"] = auc_30[model_name]["bin_auc_scores"]["Days 26-30"]
    row["auc_later"] = auc_30[model_name]["bin_auc_scores"]["After day 30"]

    rows.append(row)

metrics_df = pd.DataFrame(rows)
metrics_df

,model_label,horizon,fair_brier_skill_d1_5,fair_brier_skill_d6_10,fair_brier_skill_d11_15,fair_brier_skill_d16_20,fair_brier_skill_d21_25,fair_brier_skill_d26_30,fair_brier_d1_5,fair_brier_d6_10,...,fair_brier_d16_20,fair_brier_d21_25,fair_brier_d26_30,auc_d1_5,auc_d6_10,auc_d11_15,auc_d16_20,auc_d21_25,auc_d26_30,auc_later
0,ifs,15,0.397846,0.147049,0.046467,NaN,NaN,NaN,0.048682,0.068558,...,NaN,NaN,NaN,0.922698,0.851670,0.771822,NaN,NaN,NaN,0.927304
1,ifs,30,0.397846,0.147049,0.046467,0.049100,-0.001361,0.013516,0.048682,0.068558,...,0.079129,0.087224,0.086659,0.922698,0.851670,0.771822,0.766231,0.694732,0.721722,0.895437
2,gencast,15,0.332756,0.065693,0.052427,NaN,NaN,NaN,0.052584,0.075229,...,NaN,NaN,NaN,0.929903,0.833178,0.816743,NaN,NaN,NaN,0.929464
3,gencast,30,0.332756,0.065693,0.052427,-0.052475,-0.044604,-0.027344,0.052584,0.075229,...,0.084940,0.090560,0.088514,0.929903,0.833178,0.816743,0.774316,0.728810,0.731957,0.900925
4,fuxi-s2s,15,0.208563,0.069433,-0.155639,NaN,NaN,NaN,0.061938,0.067932,...,NaN,NaN,NaN,0.808628,0.871501,0.661179,NaN,NaN,NaN,0.872859
5,fuxi-s2s,30,0.208563,0.069433,-0.155639,-0.081604,-0.272543,-0.018465,0.061938,0.067932,...,0.094841,0.110850,0.078090,0.808628,0.871501,0.661179,0.748228,0.651966,0.774356,0.900549
6,ngcm,15,0.334993,0.124527,0.055870,NaN,NaN,NaN,0.052407,0.070492,...,NaN,NaN,NaN,0.947398,0.875928,0.824400,NaN,NaN,NaN,0.938979
7,ngcm,30,0.334993,0.124527,0.055870,-0.005738,-0.047950,-0.092803,0.052407,0.070492,...,0.081168,0.090850,0.094154,0.947398,0.875928,0.824400,0.812459,0.725694,0.682558,0.908256

In [12]:
metrics_df.to_csv(f"{config["output_dir"]}/fig2_data_recreation.csv")

In [33]:
reliability_15

{'IFS':   Bin_Range  N_Forecasts  Mean_Forecast_Prob  Observed_Frequency  Frequency  \
 0   0.0-0.1         1674               0.012               0.038      0.619
 1   0.1-0.2          161               0.182               0.205      0.060
 2   0.2-0.3          106               0.273               0.311      0.039
 3   0.3-0.4           92               0.364               0.261      0.034
 4   0.4-0.5           73               0.455               0.397      0.027
 5   0.5-0.6           51               0.545               0.412      0.019
 6   0.6-0.7           42               0.636               0.524      0.016
 7   0.7-0.8           52               0.727               0.635      0.019
 8   0.8-0.9           46               0.818               0.630      0.017
 9   0.9-1.0          407               0.986               0.953      0.151

    Error_Bar  bin_center
 0      0.005        0.05
 1      0.032        0.15
 2      0.045        0.25
 3      0.046        0.35
 4      0.057        0.45
 5      0.069        0.55
 6      0.077        0.65
 7      0.067        0.75
 8      0.071        0.85
 9      0.010        0.95  ,
 'GenCast':   Bin_Range  N_Forecasts  Mean_Forecast_Prob  Observed_Frequency  Frequency  \
 0   0.0-0.1         1697               0.009               0.038      0.628
 1   0.1-0.2          151               0.158               0.172      0.056
 2   0.2-0.3          102               0.254               0.304      0.038
 3   0.3-0.4           73               0.355               0.370      0.027
 4   0.4-0.5           62               0.451               0.290      0.023
 5   0.5-0.6           48               0.544               0.521      0.018
 6   0.6-0.7           39               0.645               0.564      0.014
 7   0.7-0.8           51               0.742               0.549      0.019
 8   0.8-0.9           51               0.846               0.608      0.019
 9   0.9-1.0          430               0.989               0.937      0.159

    Error_Bar  bin_center
 0      0.005        0.05
 1      0.031        0.15
 2      0.046        0.25
 3      0.057        0.35
 4      0.058        0.45
 5      0.072        0.55
 6      0.079        0.65
 7      0.070        0.75
 8      0.068        0.85
 9      0.012        0.95  ,
 'FuXi-S2S':   Bin_Range  N_Forecasts  Mean_Forecast_Prob  Observed_Frequency  Frequency  \
 0   0.0-0.1          575               0.004               0.052      0.694
 1   0.1-0.2           14               0.154               0.286      0.017
 2   0.2-0.3           14               0.249               0.214      0.017
 3   0.3-0.4           12               0.356               0.167      0.014
 4   0.4-0.5            7               0.457               0.571      0.008
 5   0.5-0.6           13               0.543               0.385      0.016
 6   0.6-0.7            9               0.632               0.556      0.011
 7   0.7-0.8           12               0.745               0.750      0.014
 8   0.8-0.9            9               0.845               0.556      0.011
 9   0.9-1.0          163               0.995               0.859      0.197

    Error_Bar  bin_center
 0      0.009        0.05
 1      0.121        0.15
 2      0.110        0.25
 3      0.108        0.35
 4      0.187        0.45
 5      0.135        0.55
 6      0.166        0.65
 7      0.125        0.75
 8      0.166        0.85
 9      0.027        0.95  ,
 'NGCM':   Bin_Range  N_Forecasts  Mean_Forecast_Prob  Observed_Frequency  Frequency  \
 0   0.0-0.1         1581               0.012               0.025      0.585
 1   0.1-0.2          214               0.155               0.220      0.079
 2   0.2-0.3          151               0.251               0.265      0.056
 3   0.3-0.4          101               0.349               0.317      0.037
 4   0.4-0.5           79               0.450               0.405      0.029
 5   0.5-0.6           41               0.552               0.439      0.015
 6   0.6-0.7           52               0.650               0.615      0.019
 7   0.7-0.8           45               0.740               0.622      0.017
 8   0.8-0.9           57               0.843               0.702      0.021
 9   0.9-1.0          383               0.985               0.961      0.142

    Error_Bar  bin_center
 0      0.004        0.05
 1      0.028        0.15
 2      0.036        0.25
 3      0.046        0.35
 4      0.055        0.45
 5      0.078        0.55
 6      0.067        0.65
 7      0.072        0.75
 8      0.061        0.85
 9      0.010        0.95  }

### Fig 3 -- Binned Avg. CMZ Spatial Metrics

In [13]:
# Reading in Matlab files

from scipy.io import loadmat

def load_mat_to_dict(file_path:str,
                    vars_of_interest: list = None):
    data = loadmat(file_path)
    if vars_of_interest:
        ret_dict = {var: data[var] for var in vars_of_interest}
        return ret_dict
    return data

In [14]:
load_mat_to_dict("/Users/charlieeden/Downloads/5day_forecastwindow_cmz_2019_2024.mat")

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACA64, Created on: Sat Sep 27 12:35:10 2025',
 '__version__': '1.0',
 '__globals__': [],
 'far_cmz': array([[ 5.00552672,  5.14806667,  6.14221866,  1.61055272,  8.92096044,
          4.60774198,  3.59489348,  5.85507257],
        [ 7.95982277,  8.78547899,  8.85290505,  4.26848899, 11.39773605,
          6.4457009 ,  6.9739043 ,  7.40127785],
        [10.5148626 ,  7.35800489, 12.77523487,  6.54565838, 13.09821372,
          4.49552206,  6.85812311,  4.00694431],
        [12.0407337 ,  6.28736664, 12.38162626, 13.88521342, 24.13860657,
          6.12166779, 11.62840659,  6.82676204],
        [14.46997348,  7.46808236, 17.49078923, 15.73044724, 27.4567295 ,
          6.41197107, 11.71757763, 10.33545782],
        [16.13182367, 10.74482817, 23.85337689, 20.23400135, 17.59355116,
          9.77286226, 18.68398268,  6.96542738]]),
 'mae_cmz': array([[ 4.52380952,  2.82559524,  2.352403  ,  1.51871693,  3.23525463,
          2.48729608,  2.43518519,  2.92390873],
        [ 4.93875661,  4.17808201,  3.81161265,  2.42744709,  4.92315366,
          3.3900463 ,  4.22916667,  4.04976852],
        [ 5.8787037 ,  5.45952381,  5.80594687,  4.35793651,  6.65906636,
          3.97189153,  4.42162698,  4.09186508],
        [ 5.8787037 ,  5.53677249,  6.9212522 ,  5.64917328,  8.46685957,
          5.45185185,  6.53780864,  6.14808201],
        [ 6.18888889,  5.45666667,  6.8099978 ,  7.8738481 ,  9.98910494,
          9.14803241,  7.25462963,  6.6264881 ],
        [ 6.86481481,  7.46369048,  8.31888889,  9.21891534, 10.55787037,
          6.20347222,  8.25099206,  6.67222222]]),
 'model_str': array([[array(['clim'], dtype='<U4')],
        [array(['ifs'], dtype='<U3')],
        [array(['aifs'], dtype='<U4')],
        [array(['fuxi'], dtype='<U4')],
        [array(['graphcast'], dtype='<U9')],
        [array(['gencast'], dtype='<U7')],
        [array(['fuxis2s'], dtype='<U7')],
        [array(['ngcm51'], dtype='<U6')]], dtype=object),
 'mr_cmz': array([[67.66666667, 33.55952381, 25.19444444, 44.22222222, 12.27777778,
         28.80555556, 40.        , 29.36111111],
        [52.80701754, 28.58333333, 18.4502924 , 44.50292398, 14.67836257,
         31.02339181, 33.55555556, 26.49122807],
        [39.17764726, 22.32448711, 17.84531599, 39.97521648, 14.49659804,
         30.19342343, 29.67765568, 24.93575148],
        [31.94444444, 20.33333333, 18.88888889, 34.72222222, 12.5       ,
         30.55555556, 26.11111111, 20.55555556],
        [26.00372788, 16.28467565, 20.43474686, 33.07791259, 10.13269193,
         27.48711585, 21.82194617, 16.61564073],
        [22.54524887, 16.36023021, 15.57202191, 28.46115902,  9.93246662,
         20.33239421, 18.98860399, 13.67698442]]),
 'std_er': array([[0.62342773, 0.74364861, 0.36780142, 0.2633988 , 0.41384895,
         0.7004356 , 0.93115422, 0.43533785],
        [0.5753879 , 0.24761746, 0.31806117, 0.30226602, 0.47629152,
         0.43081092, 0.27976718, 0.44307873],
        [0.70168876, 0.7169751 , 0.31873431, 0.30390861, 0.7432529 ,
         0.6807999 , 0.60163314, 0.66805414],
        [0.70168876, 1.09182   , 0.69169298, 0.60152326, 0.82021513,
         0.85028035, 1.31826779, 0.47882791],
        [0.6216929 , 1.07787857, 0.35472323, 0.76543175, 0.59277759,
         1.11067179, 0.47752559, 1.2064924 ],
        [0.76088219, 1.93650549, 1.11127849, 1.722476  , 2.2485318 ,
         0.93765148, 1.30708008, 1.70522979]])}

In [21]:
from monsoonbench.utils.forecast_window_pipeline import (
    run_multi_model_window_analysis,
    get_default_four_degree_model_specs
)

model_specs = {
        "ifs": {
            "model_type": "probabilistic",
            "expected_ens": 11,
            "mem_num": 11,
            "date_filter_year": 2024,
            "path": model_paths["IFS"],
        },
        "aifs": {
            "model_type": "deterministic",
            "expected_ens": None,
            "mem_num": None,
            "date_filter_year": 2024,
            "path": model_paths["AIFS"],
        },
        "fuxi": {
            "model_type": "deterministic",
            "expected_ens": None,
            "mem_num": None,
            "date_filter_year": 2024,
            "path": model_paths["FuXi"],
        },
        "graphcast": {
            "model_type": "deterministic",
            "expected_ens": None,
            "mem_num": None,
            "date_filter_year": 2024,
            "path": model_paths["Graphcast"],
        },
        "gencast": {
            "model_type": "probabilistic",
            "expected_ens": 51,
            "mem_num": 51,
            "date_filter_year": 2024,
            "path": model_paths["GenCast"],
        },
        "fuxi-s2s": {
            "model_type": "probabilistic",
            "expected_ens": 51,
            "mem_num": 51,
            "date_filter_year": 2022,
            "path": model_paths["FuXi-S2S"],
        },
        "ngcm": {
            "model_type": "probabilistic",
            "expected_ens": 51,
            "mem_num": 51,
            "date_filter_year": 2024,
            "path": model_paths["NGCM"],
        },
    }

fig3_spatial_cmz_data = run_multi_model_window_analysis(base_config=config,
                                model_specs=model_specs,
                                )

Running model=ifs, years=[2019, 2020, 2021, 2022, 2023]
Computing climatological onset from 124 years: 1901-2024
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1901.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1901-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1902.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1902-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1903.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1903-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1904.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1904-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1905.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1905-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1906.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1906-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1907.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1907-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1908.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1908-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1909.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1909-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1910.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1910-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1911.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1911-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1912.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1912-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1913.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1913-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1914.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1914-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1915.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1915-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1916.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1916-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1917.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1917-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1918.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1918-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1919.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1919-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1920.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1920-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1921.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1921-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1922.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1922-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1923.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1923-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1924.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1924-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1925.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1925-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1926.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1926-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1927.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1927-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1928.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1928-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1929.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1929-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1930.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1930-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1931.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1931-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1932.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1932-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1933.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1933-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1934.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1934-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1935.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1935-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1936.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1936-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1937.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1937-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1938.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1938-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1939.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1939-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1940.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1940-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1941.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1941-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1942.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1942-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1943.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1943-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1944.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1944-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1945.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1945-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1946.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1946-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1947.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1947-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1948.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1948-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1949.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1949-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1950.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1950-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1951.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1951-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1952.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1952-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1953.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1953-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1954.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1954-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1955.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1955-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1956.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1956-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1957.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1957-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1958.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1958-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1959.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1959-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1960.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1960-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1961.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1961-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1962.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1962-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1963.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1963-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1964.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1964-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1965.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1965-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1966.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1966-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1967.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1967-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1968.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1968-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1969.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1969-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1970.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1970-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1971.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1971-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1972.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1972-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1973.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1973-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1974.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1974-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1975.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1975-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1976.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1976-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1977.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1977-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1978.nc

In [62]:
for key, value in fig3_spatial_cmz_data["matrices"].items():
    value.to_csv(
        f"{config["output_dir"]}/fig3_data_recreation_{key}.csv"
    )
    print(f"CSV for {key} saved")

CSV for mae_cmz saved
CSV for far_cmz saved
CSV for mr_cmz saved
CSV for std_er saved

In [61]:
common_skills_15 = {}
common_skills_30 = {}
common_brier_15 = {}
common_brier_30 = {}
common_auc_15 = {}
common_auc_30 = {}
common_reliability_15 = {}

In [31]:
# 15 day
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    print("\n")
    print(f"Processing {model_name}")
    print("="*50)
    forecast_df = p.multi_year_forecast_obs_pairs(
            config["common_period"],
            model_forecast_dir=model_paths[model_name],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            mem_num=51,
            max_forecast_day=15,
            day_bins=config["day_bins_15"],
            date_filter_year=2022,
        )
    
    climatology_obs_df = c.multi_year_climatological_forecast_obs_pairs(
            clim_onset,
            config["common_period"],
            config["day_bins_15"],
            config["mem_num"],
            model_paths[model_name],
            date_filter_year=2022,
            file_pattern=config["file_pattern"],
            max_forecast_day=15,
            mok=config["mok"],
        )
    
    brier_forecast = p.calculate_brier_score(forecast_df)
    rps_forecast = p.calculate_rps(forecast_df)
    auc_forecast = p.calculate_auc(forecast_df)

    brier_climatology = c.calculate_brier_score_climatology(climatology_obs_df)
    rps_climatology = p.calculate_rps(climatology_obs_df)
    auc_climatology = c.calculate_auc_climatology(climatology_obs_df)


    skill_results = p.calculate_skill_scores(
            brier_forecast, rps_forecast, brier_climatology, rps_climatology
        )
    
    reliability_metrics = calculate_reliability_metrics(forecast_df)

    common_skills_15[model_name] = skill_results
    common_reliability_15[model_name] = reliability_metrics
    common_auc_15[model_name] = auc_forecast
    common_brier_15[model_name] = brier_forecast

# 30 day
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    print("\n")
    print(f"Processing {model_name}")
    print("="*50)
    forecast_df = p.multi_year_forecast_obs_pairs(
            config['common_period'],
            model_forecast_dir=model_paths[model_name],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            mem_num=51,
            max_forecast_day=30,
            day_bins=config["day_bins_30"],
            date_filter_year=2022,
        )
    
    climatology_obs_df = c.multi_year_climatological_forecast_obs_pairs(
            clim_onset,
            config["common_period"],
            config["day_bins_30"],
            config["mem_num"],
            model_paths[model_name],
            date_filter_year=2022,
            file_pattern=config["file_pattern"],
            max_forecast_day=30,
            mok=config["mok"],
        )
    
    brier_forecast = p.calculate_brier_score(forecast_df)
    rps_forecast = p.calculate_rps(forecast_df)
    auc_forecast = p.calculate_auc(forecast_df)

    brier_climatology = c.calculate_brier_score_climatology(climatology_obs_df)
    rps_climatology = p.calculate_rps(climatology_obs_df)
    auc_climatology = c.calculate_auc_climatology(climatology_obs_df)


    skill_results = p.calculate_skill_scores(
            brier_forecast, rps_forecast, brier_climatology, rps_climatology
        )
    
    common_skills_30[model_name] = skill_results  
    common_auc_30[model_name] = auc_forecast
    common_brier_30[model_name] = brier_forecast

Processing IFS
==================================================
Processing years: [2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
 2018 2019 2020 2021]
Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2004
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2004.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2004-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2004-05-02
Processing init time 6/13: 2004-06-06
Processing init time 11/13: 2004-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 583
Valid forecasts processed: 847
Generated 847 member-forecast combinations
Found onset in 309 cases
Onset rate: 0.365
✓ All init_time-lat-lon-member combinations are unique
Found onset in 309 member cases
Creating forecast-observation pairs...
Processing 77 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 308 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 146

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             77  0.635          0.727
Days 1-5                 77  0.176          0.130
Days 11-15               77  0.084          0.078
Days 6-10                77  0.105          0.065
Year 2004 completed: 308 forecast-observation pairs

==================================================
Processing year 2005
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2005.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2005-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2005-05-02
Processing init time 6/13: 2005-06-06
Processing init time 11/13: 2005-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 539
Valid forecasts processed: 891
Generated 891 member-forecast combinations
Found onset in 251 cases
Onset rate: 0.282
✓ All init_time-lat-lon-member combinations are unique
Found onset in 251 member cases
Creating forecast-observation pairs...
Processing 81 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 324 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 128

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             81  0.718          0.728
Days 1-5                 81  0.116          0.123
Days 11-15               81  0.072          0.074
Days 6-10                81  0.094          0.074
Year 2005 completed: 324 forecast-observation pairs

==================================================
Processing year 2006
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2006.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2006-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2006-05-02
Processing init time 6/13: 2006-06-06
Processing init time 11/13: 2006-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 627
Valid forecasts processed: 803
Generated 803 member-forecast combinations
Found onset in 264 cases
Onset rate: 0.329
✓ All init_time-lat-lon-member combinations are unique
Found onset in 264 member cases
Creating forecast-observation pairs...
Processing 73 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 292 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 132

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             73  0.671          0.712
Days 1-5                 73  0.149          0.110
Days 11-15               73  0.085          0.137
Days 6-10                73  0.095          0.041
Year 2006 completed: 292 forecast-observation pairs

==================================================
Processing year 2007
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2007.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2007-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2007-05-02
Processing init time 6/13: 2007-06-06
Processing init time 11/13: 2007-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 671
Valid forecasts processed: 759
Generated 759 member-forecast combinations
Found onset in 263 cases
Onset rate: 0.347
✓ All init_time-lat-lon-member combinations are unique
Found onset in 263 member cases
Creating forecast-observation pairs...
Processing 69 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 276 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 112

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             69  0.653          0.681
Days 1-5                 69  0.166          0.130
Days 11-15               69  0.066          0.130
Days 6-10                69  0.115          0.058
Year 2007 completed: 276 forecast-observation pairs

==================================================
Processing year 2008
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2008.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2008-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2008-05-02
Processing init time 6/13: 2008-06-06
Processing init time 11/13: 2008-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 737
Valid forecasts processed: 693
Generated 693 member-forecast combinations
Found onset in 301 cases
Onset rate: 0.434
✓ All init_time-lat-lon-member combinations are unique
Found onset in 301 member cases
Creating forecast-observation pairs...
Processing 63 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 252 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 117

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             63  0.566          0.683
Days 1-5                 63  0.188          0.127
Days 11-15               63  0.105          0.127
Days 6-10                63  0.141          0.063
Year 2008 completed: 252 forecast-observation pairs

==================================================
Processing year 2009
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2009.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2009-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2009-05-02
Processing init time 6/13: 2009-06-06
Processing init time 11/13: 2009-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 473
Valid forecasts processed: 957
Generated 957 member-forecast combinations
Found onset in 251 cases
Onset rate: 0.262
✓ All init_time-lat-lon-member combinations are unique
Found onset in 251 member cases
Creating forecast-observation pairs...
Processing 87 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 348 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 159

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             87  0.738          0.736
Days 1-5                 87  0.094          0.103
Days 11-15               87  0.080          0.069
Days 6-10                87  0.088          0.092
Year 2009 completed: 348 forecast-observation pairs

==================================================
Processing year 2010
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2010.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2010-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2010-05-02
Processing init time 6/13: 2010-06-06
Processing init time 11/13: 2010-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 484
Valid forecasts processed: 946
Generated 946 member-forecast combinations
Found onset in 370 cases
Onset rate: 0.391
✓ All init_time-lat-lon-member combinations are unique
Found onset in 370 member cases
Creating forecast-observation pairs...
Processing 86 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 344 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 167

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             86  0.609          0.756
Days 1-5                 86  0.229          0.047
Days 11-15               86  0.066          0.116
Days 6-10                86  0.096          0.081
Year 2010 completed: 344 forecast-observation pairs

==================================================
Processing year 2011
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2011.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2011-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2011-05-02
Processing init time 6/13: 2011-06-06
Processing init time 11/13: 2011-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 561
Valid forecasts processed: 869
Generated 869 member-forecast combinations
Found onset in 336 cases
Onset rate: 0.387
✓ All init_time-lat-lon-member combinations are unique
Found onset in 336 member cases
Creating forecast-observation pairs...
Processing 79 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 316 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 152

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             79  0.613          0.734
Days 1-5                 79  0.200          0.076
Days 11-15               79  0.078          0.089
Days 6-10                79  0.108          0.101
Year 2011 completed: 316 forecast-observation pairs

==================================================
Processing year 2012
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2012.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2012-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 11 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2012-05-02
Processing init time 6/13: 2012-06-06
Processing init time 11/13: 2012-07-11

Processing Summary:
Total potential forecasts: 1430
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 506
Valid forecasts processed: 924
Generated 924 member-forecast combinations
Found onset in 242 cases
Onset rate: 0.262
✓ All init_time-lat-lon-member combinations are unique
Found onset in 242 member cases
Creating forecast-observation pairs...
Processing 84 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 336 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250

Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2004.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2005.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2006.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2007.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2008.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2009.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2010.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2011.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2012.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2013.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2014.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2015.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2016.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2017.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2018.nc

Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2019-05-02
Processing init time 6/13: 2019-06-06
Processing init time 11/13: 2019-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2652
Valid forecasts processed: 3978
Generated 3978 member-forecast combinations
Found onset in 868 cases
Onset rate: 0.218
✓ All init_time-lat-lon-member combinations are unique
Found onset in 868 member cases
Creating forecast-observation pairs...
Processing 78 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 312 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 165

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             78  0.782          0.731
Days 1-5                 78  0.068          0.077
Days 11-15               78  0.068          0.103
Days 6-10                78  0.082          0.090
Year 2019 completed: 312 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2020-05-02
Processing init time 6/13: 2020-06-06
Processing init time 11/13: 2020-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3315
Valid forecasts processed: 3315
Generated 3315 member-forecast combinations
Found onset in 1184 cases
Onset rate: 0.357
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1184 member cases
Creating forecast-observation pairs...
Processing 65 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 260 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 139

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             65  0.643          0.692
Days 1-5                 65  0.157          0.123
Days 11-15               65  0.090          0.123
Days 6-10                65  0.110          0.062
Year 2020 completed: 260 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2021-05-02
Processing init time 6/13: 2021-06-06
Processing init time 11/13: 2021-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3366
Valid forecasts processed: 3264
Generated 3264 member-forecast combinations
Found onset in 730 cases
Onset rate: 0.224
✓ All init_time-lat-lon-member combinations are unique
Found onset in 730 member cases
Creating forecast-observation pairs...
Processing 64 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 256 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 112

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             64  0.776          0.672
Days 1-5                 64  0.092          0.109
Days 11-15               64  0.067          0.094
Days 6-10                64  0.065          0.125
Year 2021 completed: 256 forecast-observation pairs

==================================================
Combining all years
==================================================

Final Summary Statistics:
Years processed: [2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
 2018 2019 2020 2021]
Using 4-degree CMZ polygon coordinates

==================================================
Processing target year 2004
==================================================
Error processing target year 2004: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2004.nc

==================================================
Processing target year 2005
==================================================
Error processing target year 2005: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2005.nc

==================================================
Processing target year 2006
==================================================
Error processing target year 2006: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2006.nc

==================================================
Processing target year 2007
==================================================
Error processing target year 2007: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2007.nc

==================================================
Processing target year 2008
==================================================
Error processing target year 2008: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2008.nc

==================================================
Processing target year 2009
==================================================
Error processing target year 2009: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2009.nc

==================================================
Processing target year 2010
==================================================
Error processing target year 2010: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2010.nc

==================================================
Processing target year 2011
==================================================
Error processing target year 2011: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2011.nc

==================================================
Processing target year 2012
==================================================
Error processing target year 2012: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2012.nc

==================================================
Processing target year 2013
==================================================
Error processing target year 2013: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2013.nc

==================================================
Processing target year 2014
==================================================
Error processing target year 2014: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2014.nc

==================================================
Processing target year 2015
==================================================
Error processing target year 2015: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2015.nc

==================================================
Processing target year 2016
==================================================
Error processing target year 2016: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2016.nc

==================================================
Processing target year 2017
==================================================
Error processing target year 2017: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2017.nc

==================================================
Processing target year 2018
==================================================
Error processing target year 2018: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2018.nc

==================================================
Processing target year 2019
==================================================
Creating climatological forecasts for target year 2019
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 390 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 228
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                      78  0.677          0.731
Before initialization             78  0.108          0.000
Days 1-5                          78  0.065          0.077
Days 11-15                        78  0.082          0.103
Days 6-10                         78  0.067          0.090

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        83.897                   123.91
Before initialization               13.385                   123.91
Days 1-5                             8.115                   123.91
Days 11-15                          10.218                   123.91
Days 6-10                            8.295                   123.91
Target year 2019 completed: 390 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15)]
Extended bins include: 'Before initialization' and 'After day 15'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 325 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 5
Probability range: 0.000 - 1.000
Observed onset rate: 0.200
Non-zero probabilities: 175
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 15                      65  0.754          0.692
Before initialization             65  0.058          0.000
Days 1-5                          65  0.048          0.123
Days 11-15                        65  0.076          0.123
Days 6-10                         65  0.064          0.062

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 15                        93.385                  123.923
Before initialization                7.231                  123.923
Days 1-5                             5.954                  123.923
Days 11-15                           9.415                  123.923
Days 6-10                            7.938                  123.923
Target year 2020 completed: 325 pairs

==================================================
Processing target year 2021
==================================================
Creating climatological forecasts for target year 2021

Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2004.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2005.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2006.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2007.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2008.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2009.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2010.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2011.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2012.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2013.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2014.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2015.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2016.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2017.nc
Traceback (most recent call last):
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 1003, in multi_year_forecast_obs_pairs
    ProbabilisticOnsetMetrics.get_forecast_probabilistic_twice_weekly_2(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        year,
        ^^^^^
    ...<3 lines>...
        file_pattern,
        ^^^^^^^^^^^^^
    )
    ^
  File "/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py", line 120, in get_forecast_probabilistic_twice_weekly_2
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2018.nc

Processing init time 6/13: 2019-06-06
Processing init time 11/13: 2019-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2652
Valid forecasts processed: 3978
Generated 3978 member-forecast combinations
Found onset in 1869 cases
Onset rate: 0.470
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1869 member cases
Creating forecast-observation pairs...
Processing 78 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 546 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 318

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30             78  0.530          0.462
Days 1-5                 78  0.068          0.077
Days 11-15               78  0.068          0.103
Days 16-20               78  0.086          0.077
Days 21-25               78  0.078          0.115
Days 26-30               78  0.087          0.077
Days 6-10                78  0.082          0.090
Year 2019 completed: 546 forecast-observation pairs

==================================================
Processing year 2020
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2020.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2020-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2020-05-02
Processing init time 6/13: 2020-06-06
Processing init time 11/13: 2020-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3315
Valid forecasts processed: 3315
Generated 3315 member-forecast combinations
Found onset in 1882 cases
Onset rate: 0.568
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1882 member cases
Creating forecast-observation pairs...
Processing 65 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 455 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 237

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30             65  0.432          0.369
Days 1-5                 65  0.157          0.123
Days 11-15               65  0.090          0.123
Days 16-20               65  0.081          0.138
Days 21-25               65  0.068          0.077
Days 26-30               65  0.062          0.108
Days 6-10                65  0.110          0.062
Year 2020 completed: 455 forecast-observation pairs

==================================================
Processing year 2021
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2021.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2021-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2021-05-02
Processing init time 6/13: 2021-06-06
Processing init time 11/13: 2021-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3366
Valid forecasts processed: 3264
Generated 3264 member-forecast combinations
Found onset in 1546 cases
Onset rate: 0.474
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1546 member cases
Creating forecast-observation pairs...
Processing 64 forecast cases with day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Including 'after day 30' bin for members without onset in forecast window
Generated 448 forecast-observation pairs
Total bins per forecast: 7
Probability range: 0.000 - 1.000
Observed onset rate: 0.143
Non-zero probabilities: 230

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 30             64  0.526          0.328
Days 1-5                 64  0.092          0.109
Days 11-15               64  0.067          0.094
Days 16-20               64  0.059          0.125
Days 21-25               64  0.092          0.125
Days 26-30               64  0.099          0.094
Days 6-10                64  0.065          0.125
Year 2021 completed: 448 forecast-observation pairs

==================================================
Combining all years
==================================================

Final Summary Statistics:
Years processed: [2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017
 2018 2019 2020 2021]
Using 4-degree CMZ polygon coordinates

==================================================
Processing target year 2004
==================================================
Error processing target year 2004: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2004.nc

==================================================
Processing target year 2005
==================================================
Error processing target year 2005: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2005.nc

==================================================
Processing target year 2006
==================================================
Error processing target year 2006: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2006.nc

==================================================
Processing target year 2007
==================================================
Error processing target year 2007: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2007.nc

==================================================
Processing target year 2008
==================================================
Error processing target year 2008: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2008.nc

==================================================
Processing target year 2009
==================================================
Error processing target year 2009: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2009.nc

==================================================
Processing target year 2010
==================================================
Error processing target year 2010: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2010.nc

==================================================
Processing target year 2011
==================================================
Error processing target year 2011: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2011.nc

==================================================
Processing target year 2012
==================================================
Error processing target year 2012: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2012.nc

==================================================
Processing target year 2013
==================================================
Error processing target year 2013: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2013.nc

==================================================
Processing target year 2014
==================================================
Error processing target year 2014: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2014.nc

==================================================
Processing target year 2015
==================================================
Error processing target year 2015: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2015.nc

==================================================
Processing target year 2016
==================================================
Error processing target year 2016: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2016.nc

==================================================
Processing target year 2017
==================================================
Error processing target year 2017: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2017.nc

==================================================
Processing target year 2018
==================================================
Error processing target year 2018: File not found: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/rainfall_4p0/GenCast/2018.nc

==================================================
Processing target year 2019
==================================================
Creating climatological forecasts for target year 2019
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 624 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 402
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      78  0.417          0.462
Before initialization             78  0.108          0.000
Days 1-5                          78  0.065          0.077
Days 11-15                        78  0.082          0.103
Days 16-20                        78  0.088          0.077
Days 21-25                        78  0.086          0.115
Days 26-30                        78  0.086          0.077
Days 6-10                         78  0.067          0.090

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        51.667                   123.91
Before initialization               13.385                   123.91
Days 1-5                             8.115                   123.91
Days 11-15                          10.218                   123.91
Days 16-20                          10.885                   123.91
Days 21-25                          10.667                   123.91
Days 26-30                          10.679                   123.91
Days 6-10                            8.295                   123.91
Target year 2019 completed: 624 pairs

==================================================
Processing target year 2020
==================================================
Creating climatological forecasts for target year 2020
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 520 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 322
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      65  0.468          0.369
Before initialization             65  0.058          0.000
Days 1-5                          65  0.048          0.123
Days 11-15                        65  0.076          0.123
Days 16-20                        65  0.092          0.138
Days 21-25                        65  0.101          0.077
Days 26-30                        65  0.093          0.108
Days 6-10                         65  0.064          0.062

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        57.969                  123.923
Before initialization                7.231                  123.923
Days 1-5                             5.954                  123.923
Days 11-15                           9.415                  123.923
Days 16-20                          11.431                  123.923
Days 21-25                          12.492                  123.923
Days 26-30                          11.492                  123.923
Days 6-10                            7.938                  123.923
Target year 2020 completed: 520 pairs

==================================================
Processing target year 2021
==================================================
Creating climatological forecasts for target year 2021

In [32]:
rows = []
for model_name in [
    "IFS",
    "GenCast",
    "FuXi-S2S",
    "NGCM",
    ]:
    row = {}
    row["model_label"] = model_name.lower()
    row["horizon"] = 15

    row["fair_brier_skill_d1_5"] = common_skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 1-5"]
    row["fair_brier_skill_d6_10"] = common_skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 6-10"]
    row["fair_brier_skill_d11_15"] = common_skills_15[model_name]["bin_fair_brier_skill_scores"]["Days 11-15"]
    row["fair_brier_skill_d16_20"] = None
    row["fair_brier_skill_d21_25"] = None
    row["fair_brier_skill_d26_30"] = None

    row["fair_brier_d1_5"] = common_brier_15[model_name]["bin_fair_brier_scores"]["Days 1-5"]
    row["fair_brier_d6_10"] = common_brier_15[model_name]["bin_fair_brier_scores"]["Days 6-10"]
    row["fair_brier_d11_15"] = common_brier_15[model_name]["bin_fair_brier_scores"]["Days 11-15"]
    row["fair_brier_d16_20"] = None
    row["fair_brier_d21_25"] = None
    row["fair_brier_d26_30"] = None

    row["auc_d1_5"] = common_auc_15[model_name]["bin_auc_scores"]["Days 1-5"]
    row["auc_d6_10"] = common_auc_15[model_name]["bin_auc_scores"]["Days 6-10"]
    row["auc_d11_15"] = common_auc_15[model_name]["bin_auc_scores"]["Days 11-15"]
    row["auc_d16_20"] = None
    row["auc_d21_25"] = None
    row["auc_d26_30"] = None
    row["auc_later"] = common_auc_15[model_name]["bin_auc_scores"]["After day 15"]

    rows.append(row)


    row = {}
    row["model_label"] = model_name.lower()
    row["horizon"] = 30

    row["fair_brier_skill_d1_5"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 1-5"]
    row["fair_brier_skill_d6_10"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 6-10"]
    row["fair_brier_skill_d11_15"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 11-15"]
    row["fair_brier_skill_d16_20"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 16-20"]
    row["fair_brier_skill_d21_25"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 21-25"]
    row["fair_brier_skill_d26_30"] = common_skills_30[model_name]["bin_fair_brier_skill_scores"]["Days 26-30"]

    row["fair_brier_d1_5"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 1-5"]
    row["fair_brier_d6_10"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 6-10"]
    row["fair_brier_d11_15"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 11-15"]
    row["fair_brier_d16_20"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 16-20"]
    row["fair_brier_d21_25"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 21-25"]
    row["fair_brier_d26_30"] = common_brier_30[model_name]["bin_fair_brier_scores"]["Days 26-30"]

    row["auc_d1_5"] = common_auc_30[model_name]["bin_auc_scores"]["Days 1-5"]
    row["auc_d6_10"] = common_auc_30[model_name]["bin_auc_scores"]["Days 6-10"]
    row["auc_d11_15"] = common_auc_30[model_name]["bin_auc_scores"]["Days 11-15"]
    row["auc_d16_20"] = common_auc_30[model_name]["bin_auc_scores"]["Days 16-20"]
    row["auc_d21_25"] = common_auc_30[model_name]["bin_auc_scores"]["Days 21-25"]
    row["auc_d26_30"] = common_auc_30[model_name]["bin_auc_scores"]["Days 26-30"]
    row["auc_later"] = common_auc_30[model_name]["bin_auc_scores"]["After day 30"]

    rows.append(row)

common_metrics_df = pd.DataFrame(rows)
common_metrics_df

,model_label,horizon,fair_brier_skill_d1_5,fair_brier_skill_d6_10,fair_brier_skill_d11_15,fair_brier_skill_d16_20,fair_brier_skill_d21_25,fair_brier_skill_d26_30,fair_brier_d1_5,fair_brier_d6_10,...,fair_brier_d16_20,fair_brier_d21_25,fair_brier_d26_30,auc_d1_5,auc_d6_10,auc_d11_15,auc_d16_20,auc_d21_25,auc_d26_30,auc_later
0,ifs,15,0.244852,0.083944,0.112915,NaN,NaN,NaN,0.061957,0.062265,...,NaN,NaN,NaN,0.933867,0.826573,0.781372,NaN,NaN,NaN,0.933710
1,ifs,30,0.244852,0.083944,0.112915,0.027011,0.020428,0.026547,0.061957,0.062265,...,0.083511,0.077383,0.076728,0.933867,0.826573,0.781372,0.729617,0.682875,0.692172,0.903173
2,gencast,15,0.247295,-0.019477,0.057570,NaN,NaN,NaN,0.058907,0.074423,...,NaN,NaN,NaN,0.905018,0.809770,0.813391,NaN,NaN,NaN,0.910289
3,gencast,30,0.247295,-0.019477,0.057570,0.034114,-0.052971,-0.012585,0.058907,0.074423,...,0.084695,0.091723,0.077639,0.905018,0.809770,0.813391,0.806829,0.726904,0.720325,0.913482
4,fuxi-s2s,15,0.173327,0.032863,0.026668,NaN,NaN,NaN,0.068179,0.075226,...,NaN,NaN,NaN,0.893137,0.820004,0.795203,NaN,NaN,NaN,0.920527
5,fuxi-s2s,30,0.173327,0.032863,0.026668,0.028149,-0.023488,-0.005887,0.068179,0.075226,...,0.081889,0.083869,0.085724,0.893137,0.820004,0.795203,0.793127,0.765150,0.752192,0.897301
6,ngcm,15,0.181067,0.009371,0.068369,NaN,NaN,NaN,0.067191,0.067334,...,NaN,NaN,NaN,0.942232,0.837668,0.813054,NaN,NaN,NaN,0.938232
7,ngcm,30,0.181067,0.009371,0.068369,0.039376,0.002081,0.019421,0.067191,0.067334,...,0.082449,0.078832,0.077289,0.942232,0.837668,0.813054,0.778698,0.733676,0.753462,0.912899

In [64]:
common_metrics_df.to_csv(
    f"{config["output_dir"]}/fig3_common_period_data_recreation.csv"
)

### Fig 6 -- Probabilistic Metrics 4x4 lon/lat grid

In [43]:
brier_model_paths = {
        "FuXi-S2S": model_paths["FuXi-S2S"],
        "NGCM": model_paths["NGCM"],
        "IFS": model_paths["IFS"],
    }

In [44]:
from examples.paper_figures.fig6_through_12_utils import (
    calculate_gridwise_brier,
    calculate_gridwise_rps
)

forecast_dfs_15 = {}
forecast_dfs_30 = {}
for model_name, model_fp in brier_model_paths.items():
    print("=" * 80)
    print(f"Loading data from {model_name}")
    print("=" * 80)
    multi_year_df = p.multi_year_forecast_obs_pairs(
        range(2004, 2022),
        model_forecast_dir=model_fp,
        imd_folder=config["imd_folder"],
        thres_file=config["thresh_file"],
        mem_num=51 if model_name != "IFS" else 11,
        max_forecast_day=15,
        day_bins=config["day_bins_15"],
        date_filter_year=2024 if model_name != "IFS" else 2022,
    )
    forecast_dfs_15[model_name] = multi_year_df

    multi_year_df = p.multi_year_forecast_obs_pairs(
        range(2004, 2022),
        model_forecast_dir=model_fp,
        imd_folder=config["imd_folder"],
        thres_file=config["thresh_file"],
        mem_num=51 if model_name != "IFS" else 11,
        max_forecast_day=30,
        day_bins=config["day_bins_30"],
        date_filter_year=2024 if model_name != "IFS" else 2022,
    )
    forecast_dfs_30[model_name] = multi_year_df

brier_15_ds = {}
brier_30_ds = {}
rps_15_ds = {}
rps_30_ds = {}

for model, df in forecast_dfs_15.items():
    loop_grid_brier = calculate_gridwise_brier(df)
    brier_15_ds[model] = loop_grid_brier

for model, df in forecast_dfs_30.items():
    loop_grid_brier = calculate_gridwise_brier(df)
    brier_30_ds[model] = loop_grid_brier

for model, df in forecast_dfs_15.items():
    loop_grid_rps = calculate_gridwise_rps(df)
    rps_15_ds[model] = loop_grid_rps

for model, df in forecast_dfs_30.items():
    loop_grid_rps = calculate_gridwise_rps(df)
    rps_30_ds[model] = loop_grid_rps

brier_rps_graph_data_list = [brier_15_ds, brier_30_ds, rps_15_ds, rps_30_ds]

================================================================================
Loading data from FuXi-S2S
================================================================================
Processing years: range(2004, 2022)
Using 4-degree CMZ polygon coordinates

==================================================
Processing year 2004
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2004.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2004-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2004-05-02
Processing init time 6/13: 2004-06-06
Processing init time 11/13: 2004-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2703
Valid forecasts processed: 3927
Generated 3927 member-forecast combinations
Found onset in 1123 cases
Onset rate: 0.286
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1123 member cases
Creating forecast-observation pairs...
Processing 77 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 308 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 104

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             77  0.714          0.727
Days 1-5                 77  0.131          0.130
Days 11-15               77  0.072          0.078
Days 6-10                77  0.083          0.065
Year 2004 completed: 308 forecast-observation pairs

==================================================
Processing year 2005
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2005.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2005-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2005-05-02
Processing init time 6/13: 2005-06-06
Processing init time 11/13: 2005-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2499
Valid forecasts processed: 4131
Generated 4131 member-forecast combinations
Found onset in 1282 cases
Onset rate: 0.310
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1282 member cases
Creating forecast-observation pairs...
Processing 81 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 324 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 100

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             81  0.690          0.728
Days 1-5                 81  0.123          0.123
Days 11-15               81  0.069          0.074
Days 6-10                81  0.118          0.074
Year 2005 completed: 324 forecast-observation pairs

==================================================
Processing year 2006
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2006.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2006-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2006-05-02
Processing init time 6/13: 2006-06-06
Processing init time 11/13: 2006-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2907
Valid forecasts processed: 3723
Generated 3723 member-forecast combinations
Found onset in 1019 cases
Onset rate: 0.274
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1019 member cases
Creating forecast-observation pairs...
Processing 73 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 292 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 106

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             73  0.726          0.712
Days 1-5                 73  0.142          0.110
Days 11-15               73  0.069          0.137
Days 6-10                73  0.063          0.041
Year 2006 completed: 292 forecast-observation pairs

==================================================
Processing year 2007
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2007.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2007-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2007-05-02
Processing init time 6/13: 2007-06-06
Processing init time 11/13: 2007-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3111
Valid forecasts processed: 3519
Generated 3519 member-forecast combinations
Found onset in 1000 cases
Onset rate: 0.284
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1000 member cases
Creating forecast-observation pairs...
Processing 69 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 276 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 113

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             69  0.716          0.681
Days 1-5                 69  0.113          0.130
Days 11-15               69  0.114          0.130
Days 6-10                69  0.057          0.058
Year 2007 completed: 276 forecast-observation pairs

==================================================
Processing year 2008
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2008.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2008-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2008-05-02
Processing init time 6/13: 2008-06-06
Processing init time 11/13: 2008-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 3417
Valid forecasts processed: 3213
Generated 3213 member-forecast combinations
Found onset in 1266 cases
Onset rate: 0.394
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1266 member cases
Creating forecast-observation pairs...
Processing 63 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 252 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 93

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             63  0.606          0.683
Days 1-5                 63  0.186          0.127
Days 11-15               63  0.104          0.127
Days 6-10                63  0.104          0.063
Year 2008 completed: 252 forecast-observation pairs

==================================================
Processing year 2009
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2009.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2009-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2009-05-02
Processing init time 6/13: 2009-06-06
Processing init time 11/13: 2009-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2193
Valid forecasts processed: 4437
Generated 4437 member-forecast combinations
Found onset in 1074 cases
Onset rate: 0.242
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1074 member cases
Creating forecast-observation pairs...
Processing 87 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 348 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 113

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             87  0.758          0.736
Days 1-5                 87  0.107          0.103
Days 11-15               87  0.089          0.069
Days 6-10                87  0.046          0.092
Year 2009 completed: 348 forecast-observation pairs

==================================================
Processing year 2010
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2010.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2010-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2010-05-02
Processing init time 6/13: 2010-06-06
Processing init time 11/13: 2010-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2244
Valid forecasts processed: 4386
Generated 4386 member-forecast combinations
Found onset in 1705 cases
Onset rate: 0.389
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1705 member cases
Creating forecast-observation pairs...
Processing 86 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 344 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 130

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             86  0.611          0.756
Days 1-5                 86  0.194          0.047
Days 11-15               86  0.091          0.116
Days 6-10                86  0.104          0.081
Year 2010 completed: 344 forecast-observation pairs

==================================================
Processing year 2011
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2011.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2011-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2011-05-02
Processing init time 6/13: 2011-06-06
Processing init time 11/13: 2011-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2601
Valid forecasts processed: 4029
Generated 4029 member-forecast combinations
Found onset in 1342 cases
Onset rate: 0.333
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1342 member cases
Creating forecast-observation pairs...
Processing 79 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 316 forecast-observation pairs
Total bins per forecast: 4
Probability range: 0.000 - 1.000
Observed onset rate: 0.250
Non-zero probabilities: 136

Distribution across bins:
             predicted_prob        observed_onset
                      count   mean           mean
bin_label
After day 15             79  0.667          0.734
Days 1-5                 79  0.117          0.076
Days 11-15               79  0.115          0.089
Days 6-10                79  0.101          0.101
Year 2011 completed: 316 forecast-observation pairs

==================================================
Processing year 2012
==================================================
Loading S2S model data...
Loading IMD rainfall data...
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/2012.nc
Renamed dimensions: {'TIME': 'time'}
Detecting observed onset...
Using MOK date (June 2nd) (2012-06-02) as start date for onset detection
Found onset in 100 out of 100 grid points
Computing onset for all ensemble members...
Processing 13 init times x 10 unique locations x 51 members...
Unique lat-lon pairs: [(np.float64(76.0), np.float64(20.0)), (np.float64(80.0), np.float64(20.0)), (np.float64(84.0), np.float64(20.0)), (np.float64(72.0), np.float64(24.0)), (np.float64(76.0), np.float64(24.0)), (np.float64(80.0), np.float64(24.0)), (np.float64(84.0), np.float64(24.0)), (np.float64(72.0), np.float64(28.0)), (np.float64(76.0), np.float64(28.0)), (np.float64(80.0), np.float64(28.0))]
Using MOK (June 2nd filter) for onset detection
Processing init time 1/13: 2012-05-02
Processing init time 6/13: 2012-06-06
Processing init time 11/13: 2012-07-11

Processing Summary:
Total potential forecasts: 6630
Skipped (no observed onset): 0
Skipped (initialized after observed onset): 2346
Valid forecasts processed: 4284
Generated 4284 member-forecast combinations
Found onset in 1030 cases
Onset rate: 0.240
✓ All init_time-lat-lon-member combinations are unique
Found onset in 1030 member cases
Creating forecast-observation pairs...
Processing 84 forecast cases with day bins: [(1, 5), (6, 10), (11, 15)]
Including 'after day 15' bin for members without onset in forecast window
Generated 336 forecast-observation pairs

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

Brier Score: 0.0906
Fair Brier Score: 0.0899
Brier Score: 0.0886
Fair Brier Score: 0.0881
Brier Score: 0.0870
Fair Brier Score: 0.0865
Brier Score: 0.0757
Fair Brier Score: 0.0752
Brier Score: 0.0627
Fair Brier Score: 0.0622
Brier Score: 0.0722
Fair Brier Score: 0.0716
Brier Score: 0.0858
Fair Brier Score: 0.0853
Brier Score: 0.0943
Fair Brier Score: 0.0940
Brier Score: 0.0583
Fair Brier Score: 0.0577
Brier Score: 0.0825
Fair Brier Score: 0.0819

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

Brier Score: 0.1140
Fair Brier Score: 0.1126
Brier Score: 0.0937
Fair Brier Score: 0.0925
Brier Score: 0.0989
Fair Brier Score: 0.0977
Brier Score: 0.0698
Fair Brier Score: 0.0688
Brier Score: 0.0660
Fair Brier Score: 0.0648
Brier Score: 0.0765
Fair Brier Score: 0.0754
Brier Score: 0.0931
Fair Brier Score: 0.0919
Brier Score: 0.0715
Fair Brier Score: 0.0704

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

Brier Score: 0.0710
Fair Brier Score: 0.0695
Brier Score: 0.0715
Fair Brier Score: 0.0702
Brier Score: 0.1089
Fair Brier Score: 0.1024
Brier Score: 0.0844
Fair Brier Score: 0.0790
Brier Score: 0.0739
Fair Brier Score: 0.0686
Brier Score: 0.0731
Fair Brier Score: 0.0683

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

Brier Score: 0.0635
Fair Brier Score: 0.0580
Brier Score: 0.0727
Fair Brier Score: 0.0675
Brier Score: 0.0803
Fair Brier Score: 0.0753
Brier Score: 0.0761
Fair Brier Score: 0.0721
Brier Score: 0.0706
Fair Brier Score: 0.0649
Brier Score: 0.0785
Fair Brier Score: 0.0731
Brier Score: 0.0976
Fair Brier Score: 0.0965
Brier Score: 0.0895
Fair Brier Score: 0.0885
Brier Score: 0.0942
Fair Brier Score: 0.0933
Brier Score: 0.0760
Fair Brier Score: 0.0749
Brier Score: 0.0713
Fair Brier Score: 0.0703
Brier Score: 0.0779
Fair Brier Score: 0.0770

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

Brier Score: 0.0861
Fair Brier Score: 0.0852
Brier Score: 0.0960
Fair Brier Score: 0.0952
Brier Score: 0.0660
Fair Brier Score: 0.0649
Brier Score: 0.0905
Fair Brier Score: 0.0895
Brier Score: 0.1087
Fair Brier Score: 0.1072
Brier Score: 0.0920
Fair Brier Score: 0.0905
Brier Score: 0.1005
Fair Brier Score: 0.0992
Brier Score: 0.0763
Fair Brier Score: 0.0749
Brier Score: 0.0721
Fair Brier Score: 0.0707
Brier Score: 0.0814
Fair Brier Score: 0.0801
Brier Score: 0.0909
Fair Brier Score: 0.0895
Brier Score: 0.0829
Fair Brier Score: 0.0816
Brier Score: 0.0779
Fair Brier Score: 0.0764
Brier Score: 0.0793
Fair Brier Score: 0.0779
Brier Score: 0.1029
Fair Brier Score: 0.0960
Brier Score: 0.0871
Fair Brier Score: 0.0806
Brier Score: 0.0843
Fair Brier Score: 0.0780
Brier Score: 0.0807
Fair Brier Score: 0.0752
Brier Score: 0.0761
Fair Brier Score: 0.0698
Brier Score: 0.0794
Fair Brier Score: 0.0734
Brier Score: 0.0831
Fair Brier Score: 0.0771
Brier Score: 0.0950
Fair Brier Score: 0.0902
Brier Score: 0.0755
Fair Brier Score: 0.0693
Brier Score: 0.0821
Fair Brier Score: 0.0760

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

RPS: 0.3368
Fair RPS: 0.3352
Number of forecasts: 123
RPS: 0.2143
Fair RPS: 0.2130
Number of forecasts: 122
RPS: 0.2616
Fair RPS: 0.2603
Number of forecasts: 121
RPS: 0.2599
Fair RPS: 0.2587
Number of forecasts: 148
RPS: 0.2003
Fair RPS: 0.1990
Number of forecasts: 141
RPS: 0.2443
Fair RPS: 0.2429
Number of forecasts: 142
RPS: 0.2711
Fair RPS: 0.2700
Number of forecasts: 132
RPS: 0.3884
Fair RPS: 0.3876
Number of forecasts: 143
RPS: 0.1459
Fair RPS: 0.1443
Number of forecasts: 149
RPS: 0.2218
Fair RPS: 0.2202
Number of forecasts: 138
RPS: 0.4333
Fair RPS: 0.4295
Number of forecasts: 235
RPS: 0.2612
Fair RPS: 0.2578
Number of forecasts: 236
RPS: 0.3121
Fair RPS: 0.3092
Number of forecasts: 233
RPS: 0.2143
Fair RPS: 0.2112
Number of forecasts: 285
RPS: 0.2039
Fair RPS: 0.2007
Number of forecasts: 272
RPS: 0.2584
Fair RPS: 0.2553
Number of forecasts: 272
RPS: 0.3099
Fair RPS: 0.3069
Number of forecasts: 249
RPS: 0.2107
Fair RPS: 0.2072
Number of forecasts: 274
RPS: 0.2285
Fair RPS: 0.2242
Number of forecasts: 288
RPS: 0.2191
Fair RPS: 0.2155
Number of forecasts: 266
RPS: 0.3972
Fair RPS: 0.3766
Number of forecasts: 123
RPS: 0.2585
Fair RPS: 0.2437
Number of forecasts: 122
RPS: 0.2422
Fair RPS: 0.2276
Number of forecasts: 121
RPS: 0.2302
Fair RPS: 0.2152
Number of forecasts: 148
RPS: 0.1893
Fair RPS: 0.1742
Number of forecasts: 141
RPS: 0.2627
Fair RPS: 0.2478
Number of forecasts: 142
RPS: 0.2732
Fair RPS: 0.2596
Number of forecasts: 132
RPS: 0.2437
Fair RPS: 0.2317
Number of forecasts: 143
RPS: 0.2155
Fair RPS: 0.1983
Number of forecasts: 149
RPS: 0.2617
Fair RPS: 0.2461
Number of forecasts: 138
RPS: 0.8538
Fair RPS: 0.8477
Number of forecasts: 123
RPS: 0.4807
Fair RPS: 0.4759
Number of forecasts: 122
RPS: 0.5760
Fair RPS: 0.5718
Number of forecasts: 121
RPS: 0.6118
Fair RPS: 0.6053
Number of forecasts: 148
RPS: 0.4200
Fair RPS: 0.4142
Number of forecasts: 141
RPS: 0.5799
Fair RPS: 0.5753
Number of forecasts: 142
RPS: 0.5697
Fair RPS: 0.5656
Number of forecasts: 132
RPS: 1.0222
Fair RPS: 1.0162
Number of forecasts: 143
RPS: 0.4398
Fair RPS: 0.4335
Number of forecasts: 149
RPS: 0.5463
Fair RPS: 0.5411
Number of forecasts: 138
RPS: 0.9931
Fair RPS: 0.9841
Number of forecasts: 235
RPS: 0.5495
Fair RPS: 0.5413
Number of forecasts: 236
RPS: 0.6425
Fair RPS: 0.6352
Number of forecasts: 233
RPS: 0.5636
Fair RPS: 0.5543
Number of forecasts: 285
RPS: 0.4365
Fair RPS: 0.4276
Number of forecasts: 272
RPS: 0.6277
Fair RPS: 0.6197
Number of forecasts: 272
RPS: 0.6233
Fair RPS: 0.6154
Number of forecasts: 249
RPS: 0.6150
Fair RPS: 0.6045
Number of forecasts: 274
RPS: 0.6065
Fair RPS: 0.5961
Number of forecasts: 288
RPS: 0.5193
Fair RPS: 0.5104
Number of forecasts: 266
RPS: 0.9316
Fair RPS: 0.8850
Number of forecasts: 123
RPS: 0.5318
Fair RPS: 0.4934
Number of forecasts: 122
RPS: 0.4872
Fair RPS: 0.4508
Number of forecasts: 121
RPS: 0.5919
Fair RPS: 0.5520
Number of forecasts: 148
RPS: 0.4315
Fair RPS: 0.3932
Number of forecasts: 141
RPS: 0.6204
Fair RPS: 0.5839
Number of forecasts: 142
RPS: 0.5662
Fair RPS: 0.5313
Number of forecasts: 132
RPS: 0.7525
Fair RPS: 0.7147
Number of forecasts: 143
RPS: 0.5947
Fair RPS: 0.5520
Number of forecasts: 149
RPS: 0.5713
Fair RPS: 0.5332
Number of forecasts: 138

In [71]:
# brier climatology
climatology_obs_df = c.multi_year_climatological_forecast_obs_pairs(
            clim_onset,
            config["common_period"],
            config["day_bins_30"],
            config["mem_num"],
            model_paths[model_name],
            date_filter_year=2022,
            file_pattern=config["file_pattern"],
            max_forecast_day=30,
            mok=config["mok"],
        )

Using 4-degree CMZ polygon coordinates

==================================================
Processing target year 2004
==================================================
Creating climatological forecasts for target year 2004
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 616 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 406
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      77  0.408          0.442
Before initialization             77  0.141          0.000
Days 1-5                          77  0.050          0.130
Days 11-15                        77  0.072          0.078
Days 16-20                        77  0.086          0.117
Days 21-25                        77  0.092          0.104
Days 26-30                        77  0.085          0.065
Days 6-10                         77  0.064          0.065

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        50.584                  123.831
Before initialization               17.416                  123.831
Days 1-5                             6.247                  123.831
Days 11-15                           8.961                  123.831
Days 16-20                          10.662                  123.831
Days 21-25                          11.442                  123.831
Days 26-30                          10.571                  123.831
Days 6-10                            7.948                  123.831
Target year 2004 completed: 616 pairs

==================================================
Processing target year 2005
==================================================
Creating climatological forecasts for target year 2005
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 648 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 422
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      81  0.404          0.457
Before initialization             81  0.122          0.000
Days 1-5                          81  0.067          0.123
Days 11-15                        81  0.081          0.074
Days 16-20                        81  0.088          0.099
Days 21-25                        81  0.085          0.123
Days 26-30                        81  0.084          0.049
Days 6-10                         81  0.068          0.074

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        50.049                  123.889
Before initialization               15.136                  123.889
Days 1-5                             8.333                  123.889
Days 11-15                          10.086                  123.889
Days 16-20                          10.852                  123.889
Days 21-25                          10.593                  123.889
Days 26-30                          10.420                  123.889
Days 6-10                            8.420                  123.889
Target year 2005 completed: 648 pairs

==================================================
Processing target year 2006
==================================================
Creating climatological forecasts for target year 2006
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 584 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 370
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      73  0.447          0.438
Before initialization             73  0.100          0.000
Days 1-5                          73  0.056          0.110
Days 11-15                        73  0.075          0.137
Days 16-20                        73  0.086          0.110
Days 21-25                        73  0.089          0.068
Days 26-30                        73  0.090          0.096
Days 6-10                         73  0.057          0.041

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        55.356                  123.877
Before initialization               12.438                  123.877
Days 1-5                             6.877                  123.877
Days 11-15                           9.315                  123.877
Days 16-20                          10.685                  123.877
Days 21-25                          10.986                  123.877
Days 26-30                          11.123                  123.877
Days 6-10                            7.096                  123.877
Target year 2006 completed: 584 pairs

==================================================
Processing target year 2007
==================================================
Creating climatological forecasts for target year 2007
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 552 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 338
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      69  0.470          0.377
Before initialization             69  0.062          0.000
Days 1-5                          69  0.052          0.130
Days 11-15                        69  0.079          0.130
Days 16-20                        69  0.092          0.116
Days 21-25                        69  0.093          0.058
Days 26-30                        69  0.096          0.130
Days 6-10                         69  0.058          0.058

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        58.188                  123.899
Before initialization                7.681                  123.899
Days 1-5                             6.391                  123.899
Days 11-15                           9.768                  123.899
Days 16-20                          11.377                  123.899
Days 21-25                          11.478                  123.899
Days 26-30                          11.870                  123.899
Days 6-10                            7.145                  123.899
Target year 2007 completed: 552 pairs

==================================================
Processing target year 2008
==================================================
Creating climatological forecasts for target year 2008
Using 124 years as ensemble members: [np.int64(1901), np.int64(1902), np.int64(1903), np.int64(1904), np.int64(1905), np.int64(1906), np.int64(1907), np.int64(1908), np.int64(1909), np.int64(1910), np.int64(1911), np.int64(1912), np.int64(1913), np.int64(1914), np.int64(1915), np.int64(1916), np.int64(1917), np.int64(1918), np.int64(1919), np.int64(1920), np.int64(1921), np.int64(1922), np.int64(1923), np.int64(1924), np.int64(1925), np.int64(1926), np.int64(1927), np.int64(1928), np.int64(1929), np.int64(1930), np.int64(1931), np.int64(1932), np.int64(1933), np.int64(1934), np.int64(1935), np.int64(1936), np.int64(1937), np.int64(1938), np.int64(1939), np.int64(1940), np.int64(1941), np.int64(1942), np.int64(1943), np.int64(1944), np.int64(1945), np.int64(1946), np.int64(1947), np.int64(1948), np.int64(1949), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
Processing 13 initialization dates
Day bins: [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25), (26, 30)]
Extended bins include: 'Before initialization' and 'After day 30'
Using day-of-year method for onset comparison
Processing 10 unique lat-lon pairs
Generated 504 climatological forecast-observation pairs
Unique lat-lon pairs processed: 10
Total bins per forecast: 8
Probability range: 0.000 - 1.000
Observed onset rate: 0.125
Non-zero probabilities: 291
Unique locations in output: 10

Distribution across bins:
                      predicted_prob        observed_onset  \
                               count   mean           mean
bin_label
After day 30                      63  0.488          0.349
Before initialization             63  0.096          0.000
Days 1-5                          63  0.032          0.127
Days 11-15                        63  0.062          0.127
Days 16-20                        63  0.084          0.143
Days 21-25                        63  0.097          0.127
Days 26-30                        63  0.094          0.063
Days 6-10                         63  0.046          0.063

                      n_contributing_years total_members_with_onset
                                      mean                     mean
bin_label
After day 30                        60.429                  123.905
Before initialization               11.952                  123.905
Days 1-5                             4.000                  123.905
Days 11-15                           7.698                  123.905

In [78]:
test = forecast_dfs_15["IFS"]
test = test.loc[
(test["lat"] == 20.0) & (test["lon"] == 76.0)
]

In [98]:
import warnings
import traceback

warnings.filterwarnings('error', category=RuntimeWarning)

ifs_test = forecast_dfs_15["IFS"]
clim_brier = c.calculate_brier_score_climatology(climatology_obs_df)
clim_rps = p.calculate_rps(climatology_obs_df)
rows= []
for lat in ifs_test.lat.unique():
    for lon in ifs_test.lon.unique():
        print("="*50)
        print(f"Calculating for {lat}, {lon} pair")
        print("="*50)
        row = {}
        loop_df = ifs_test.loc[
            (ifs_test["lat"] == lat) & (ifs_test["lon"] == lon)
            ].copy()

        if loop_df.empty:
            print(f"Skipping {lat}, {lon} — no data")
            continue
        else:
            loop_brier = p.calculate_brier_score(loop_df)
            loop_rps = p.calculate_rps(loop_df)
            skill_scores = p.calculate_skill_scores(
                brier_forecast=loop_brier,
                rps_forecast=loop_rps,
                brier_climatology=clim_brier,
                rps_climatology=clim_rps
            )
            row["BSS"] = skill_scores["fair_brier_skill_score"]
            row["RPS"] = skill_scores["fair_rps_skill_score"]
            row["lat"] = lat
            row["lon"] = lon
            rows.append(row)

# pd.DataFrame(rows)

Calculating Brier Score excluding 'Before initialization' bin
Original samples: 10872, After filtering: 9513
Brier Score (excluding 'Before initialization'): 0.0852
Fair Brier Score (excluding 'Before initialization'): 0.0846
Bins included in calculation: ['After day 30', 'Days 1-5', 'Days 11-15', 'Days 16-20', 'Days 21-25', 'Days 26-30', 'Days 6-10']
RPS: 0.7375
Fair RPS: 0.7327
Number of forecasts: 1359
==================================================
Calculating for 20.0, 76.0 pair
==================================================
Brier Score: 0.1089
Fair Brier Score: 0.1024
RPS: 0.3972
Fair RPS: 0.3766
Number of forecasts: 123
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): -0.2102
Fair RPS Skill Score (1-15 day): 0.4859

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = -0.2846
  Days 6-10: Fair BSS = 0.1171
  Days 11-15: Fair BSS = -0.1772

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         -0.2102            -0.2846      0.1171       -0.1772
Fair RPS Skill Score           0.4859             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.1024
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: -0.2102

Forecast Fair RPS : 0.3766
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.4859

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.1054
    Climatology: 0.0820
    Skill Score: -0.2846
  Days 6-10:
    Forecast: 0.0600
    Climatology: 0.0680
    Skill Score: 0.1171
  Days 11-15:
    Forecast: 0.0962
    Climatology: 0.0817
    Skill Score: -0.1772
==================================================
Calculating for 20.0, 80.0 pair
==================================================
Brier Score: 0.0844
Fair Brier Score: 0.0790
RPS: 0.2585
Fair RPS: 0.2437
Number of forecasts: 122
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.0661
Fair RPS Skill Score (1-15 day): 0.6674

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.0100
  Days 6-10: Fair BSS = -0.1665
  Days 11-15: Fair BSS = 0.0592

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.0661             0.0100       -0.1665      0.0592
Fair RPS Skill Score           0.6674             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0790
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.0661

Forecast Fair RPS : 0.2437
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.6674

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0812
    Climatology: 0.0820
    Skill Score: 0.0100
  Days 6-10:
    Forecast: 0.0793
    Climatology: 0.0680
    Skill Score: -0.1665
  Days 11-15:
    Forecast: 0.0769
    Climatology: 0.0817
    Skill Score: 0.0592
==================================================
Calculating for 20.0, 84.0 pair
==================================================
Brier Score: 0.0739
Fair Brier Score: 0.0686
RPS: 0.2422
Fair RPS: 0.2276
Number of forecasts: 121
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.1889
Fair RPS Skill Score (1-15 day): 0.6893

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.2363
  Days 6-10: Fair BSS = 0.2859
  Days 11-15: Fair BSS = -0.1250

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.1889             0.2363       0.2859       -0.1250
Fair RPS Skill Score           0.6893             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0686
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.1889

Forecast Fair RPS : 0.2276
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.6893

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0627
    Climatology: 0.0820
    Skill Score: 0.2363
  Days 6-10:
    Forecast: 0.0485
    Climatology: 0.0680
    Skill Score: 0.2859
  Days 11-15:
    Forecast: 0.0920
    Climatology: 0.0817
    Skill Score: -0.1250
==================================================
Calculating for 20.0, 72.0 pair
==================================================
Skipping 20.0, 72.0 — no data
==================================================
Calculating for 24.0, 76.0 pair
==================================================
Brier Score: 0.0635
Fair Brier Score: 0.0580
RPS: 0.1893
Fair RPS: 0.1742
Number of forecasts: 141
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.3142
Fair RPS Skill Score (1-15 day): 0.7622

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.5034
  Days 6-10: Fair BSS = 0.0230
  Days 11-15: Fair BSS = 0.2176

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.3142             0.5034       0.0230       0.2176
Fair RPS Skill Score           0.7622             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0580
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.3142

Forecast Fair RPS : 0.1742
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.7622

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0407
    Climatology: 0.0820
    Skill Score: 0.5034
  Days 6-10:
    Forecast: 0.0664
    Climatology: 0.0680
    Skill Score: 0.0230
  Days 11-15:
    Forecast: 0.0640
    Climatology: 0.0817
    Skill Score: 0.2176
==================================================
Calculating for 24.0, 80.0 pair
==================================================
Brier Score: 0.0727
Fair Brier Score: 0.0675
RPS: 0.2627
Fair RPS: 0.2478
Number of forecasts: 142
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.2025
Fair RPS Skill Score (1-15 day): 0.6618

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.3914
  Days 6-10: Fair BSS = 0.2032
  Days 11-15: Fair BSS = 0.2450

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.2025             0.3914       0.2032       0.2450
Fair RPS Skill Score           0.6618             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0675
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.2025

Forecast Fair RPS : 0.2478
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.6618

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0499
    Climatology: 0.0820
    Skill Score: 0.3914
  Days 6-10:
    Forecast: 0.0542
    Climatology: 0.0680
    Skill Score: 0.2032
  Days 11-15:
    Forecast: 0.0617
    Climatology: 0.0817
    Skill Score: 0.2450
==================================================
Calculating for 24.0, 84.0 pair
==================================================
Brier Score: 0.0803
Fair Brier Score: 0.0753
RPS: 0.2732
Fair RPS: 0.2596
Number of forecasts: 132
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.1104
Fair RPS Skill Score (1-15 day): 0.6456

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.3100
  Days 6-10: Fair BSS = 0.1691
  Days 11-15: Fair BSS = 0.1305

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.1104             0.3100       0.1691       0.1305
Fair RPS Skill Score           0.6456             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0753
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.1104

Forecast Fair RPS : 0.2596
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.6456

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0566
    Climatology: 0.0820
    Skill Score: 0.3100
  Days 6-10:
    Forecast: 0.0565
    Climatology: 0.0680
    Skill Score: 0.1691
  Days 11-15:
    Forecast: 0.0711
    Climatology: 0.0817
    Skill Score: 0.1305
==================================================
Calculating for 24.0, 72.0 pair
==================================================
Brier Score: 0.0731
Fair Brier Score: 0.0683
RPS: 0.2302
Fair RPS: 0.2152
Number of forecasts: 148
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.1928
Fair RPS Skill Score (1-15 day): 0.7062

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.3172
  Days 6-10: Fair BSS = 0.0403
  Days 11-15: Fair BSS = 0.1163

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.1928             0.3172       0.0403       0.1163
Fair RPS Skill Score           0.7062             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0683
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.1928

Forecast Fair RPS : 0.2152
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.7062

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0560
    Climatology: 0.0820
    Skill Score: 0.3172
  Days 6-10:
    Forecast: 0.0652
    Climatology: 0.0680
    Skill Score: 0.0403
  Days 11-15:
    Forecast: 0.0722
    Climatology: 0.0817
    Skill Score: 0.1163
==================================================
Calculating for 28.0, 76.0 pair
==================================================
Brier Score: 0.0706
Fair Brier Score: 0.0649
RPS: 0.2155
Fair RPS: 0.1983
Number of forecasts: 149
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.2335
Fair RPS Skill Score (1-15 day): 0.7294

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.4438
  Days 6-10: Fair BSS = 0.2550
  Days 11-15: Fair BSS = 0.1640

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.2335             0.4438       0.2550       0.1640
Fair RPS Skill Score           0.7294             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0649
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.2335

Forecast Fair RPS : 0.1983
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.7294

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0456
    Climatology: 0.0820
    Skill Score: 0.4438
  Days 6-10:
    Forecast: 0.0506
    Climatology: 0.0680
    Skill Score: 0.2550
  Days 11-15:
    Forecast: 0.0683
    Climatology: 0.0817
    Skill Score: 0.1640
==================================================
Calculating for 28.0, 80.0 pair
==================================================
Brier Score: 0.0785
Fair Brier Score: 0.0731
RPS: 0.2617
Fair RPS: 0.2461
Number of forecasts: 138
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): 0.1362
Fair RPS Skill Score (1-15 day): 0.6641

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = 0.1023
  Days 6-10: Fair BSS = -0.0952
  Days 11-15: Fair BSS = 0.2489

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         0.1362             0.1023       -0.0952      0.2489
Fair RPS Skill Score           0.6641             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.0731
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: 0.1362

Forecast Fair RPS : 0.2461
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.6641

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.0736
    Climatology: 0.0820
    Skill Score: 0.1023
  Days 6-10:
    Forecast: 0.0744
    Climatology: 0.0680
    Skill Score: -0.0952
  Days 11-15:
    Forecast: 0.0614
    Climatology: 0.0817
    Skill Score: 0.2489
==================================================

In [79]:
test

,init_time,lat,lon,bin_start,bin_end,bin_label,predicted_prob,observed_onset,members_with_onset,total_members,year,obs_onset_date,bin_index,squared_diff,fair_brier_component
0,2004-05-02,20.0,76.0,1,5.0,Days 1-5,0.000000,0,0,11,2004,2004-06-08,0,0.000000,0.000000
1,2004-05-02,20.0,76.0,6,10.0,Days 6-10,0.000000,0,0,11,2004,2004-06-08,1,0.000000,0.000000
2,2004-05-02,20.0,76.0,11,15.0,Days 11-15,0.000000,0,0,11,2004,2004-06-08,2,0.000000,0.000000
3,2004-05-02,20.0,76.0,16,inf,After day 15,1.000000,1,11,11,2004,2004-06-08,3,0.000000,0.000000
40,2004-05-09,20.0,76.0,1,5.0,Days 1-5,0.000000,0,0,11,2004,2004-06-08,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5303,2021-05-23,20.0,76.0,16,inf,After day 15,0.727273,0,8,11,2021,2021-06-05,3,0.528926,0.509091
5340,2021-05-30,20.0,76.0,1,5.0,Days 1-5,0.909091,0,10,11,2021,2021-06-05,0,0.826446,0.818182
5341,2021-05-30,20.0,76.0,6,10.0,Days 6-10,0.000000,1,0,11,2021,2021-06-05,1,1.000000,1.000000
5342,2021-05-30,20.0,76.0,11,15.0,Days 11-15,0.090909,0,1,11,2021,2021-06-05,2,0.008264,0.000000
5343,2021-05-30,20.0,76.0,16,inf,After day 15,0.000000,0,0,11,2021,2021-06-05,3,0.000000,0.000000

In [80]:
ifs_rps = p.calculate_rps(test)
ifs_brier = p.calculate_brier_score(test)

p.calculate_skill_scores(
    brier_forecast=ifs_brier,
    rps_forecast=ifs_rps,
    brier_climatology=clim_brier,
    rps_climatology=clim_rps
)

RPS: 0.3972
Fair RPS: 0.3766
Number of forecasts: 123
Brier Score: 0.1089
Fair Brier Score: 0.1024
Calculating Brier Score excluding 'Before initialization' bin
Original samples: 10872, After filtering: 9513
Brier Score (excluding 'Before initialization'): 0.0852
Fair Brier Score (excluding 'Before initialization'): 0.0846
Bins included in calculation: ['After day 30', 'Days 1-5', 'Days 11-15', 'Days 16-20', 'Days 21-25', 'Days 26-30', 'Days 6-10']

/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["squared_diff"] = squared_diffs
/Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/monsoonbench/metrics/probabilistic.py:1119: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forecast_obs_df["fair_brier_component"] = fair_brier_components

RPS: 0.7375
Fair RPS: 0.7327
Number of forecasts: 1359
============================================================
SKILL SCORE CALCULATIONS
============================================================
Fair Brier Skill Score (1-15 day): -0.2102
Fair RPS Skill Score (1-15 day): 0.4859

Automatically detected target bins: ['Days 1-5', 'Days 6-10', 'Days 11-15']
Excluded bins: []

Bin-wise Fair Brier Skill Scores:
  Days 1-5: Fair BSS = -0.2846
  Days 6-10: Fair BSS = 0.1171
  Days 11-15: Fair BSS = -0.1772

====================================================================================
SKILL SCORE SUMMARY TABLE
====================================================================================
Metric                         Overall (1-15 day) 1-5          6-10         11-15
------------------------------------------------------------------------------------
Fair Brier Skill Score         -0.2102            -0.2846      0.1171       -0.1772
Fair RPS Skill Score           0.4859             N/A          N/A          N/A
------------------------------------------------------------------------------------

Interpretation Guide:
• Positive skill scores indicate forecast is better than climatology
• Negative skill scores indicate forecast is worse than climatology
• Skill score = 0 means forecast equals climatology
• Perfect score = 1.0

============================================================
DETAILED RESULTS
============================================================

Forecast Fair Brier Score : 0.1024
Climatology Fair Brier Score : 0.0846
Fair Brier Skill Score: -0.2102

Forecast Fair RPS : 0.3766
Climatology Fair RPS : 0.7327
Fair RPS Skill Score: 0.4859

Bin-wise Fair Brier Score Comparisons:
  Days 1-5:
    Forecast: 0.1054
    Climatology: 0.0820
    Skill Score: -0.2846
  Days 6-10:
    Forecast: 0.0600
    Climatology: 0.0680
    Skill Score: 0.1171
  Days 11-15:
    Forecast: 0.0962
    Climatology: 0.0817
    Skill Score: -0.1772

{'fair_brier_skill_score': np.float64(-0.2101897945370823),
 'fair_rps_skill_score': np.float64(0.4859196760700001),
 'bin_fair_brier_skill_scores': {'Days 1-5': -0.2845795673324858,
  'Days 6-10': 0.11705038940192203,
  'Days 11-15': -0.17722929869020065}}

In [ ]:
# Climatology brier scores

### Fig. 7 - 12 -- Spatial Metrics 4x4 lon/lat grid

In [34]:
model_years = {
    "FuXi S2S": [2019, 2020, 2021],
    "IFS": [2019, 2020, 2021, 2022, 2023],
    "Standard": [2019, 2020, 2021, 2022, 2023, 2024],
}

In [37]:
# 15 day
metrics_df_clim_15, onset_da_clim_15 = (
        c.compute_climatology_baseline_multiple_years(
            years=model_years["Standard"],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            tolerance_days=3,
            verification_window=1,
            forecast_days=15,
            max_forecast_day=15,
            mok=True,
            onset_window=5,
            mok_month=6,
            mok_day=2,
        )
    )

spatial_clim_15_day = c.create_spatial_far_mr_mae(
        metrics_df_clim_15, dict.fromkeys(model_years["Standard"], onset_da_clim_15)
    )

model_dfs_15 = {}
model_onsets_15 = {}

for model_name, model_fp in prob_model_paths.items():
    print("=" * 80)
    print(f"Loading data from {model_name}")
    print("=" * 80)
    probabilistic_df_15, onset_da_dict_15 = (
        p.compute_metrics_multiple_years(
            years=(
                model_years[model_name]
                if model_name in model_years.keys()
                else model_years["Standard"]
            ),
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            model_forecast_dir=model_fp,
            tolerance_days=3,
            verification_window=1,
            forecast_days=15,
            max_forecast_day=15,
            mok=True,
            onset_window=5,
            mok_month=6,
            mok_day=2,
        )
    )

    model_dfs_15[model_name] = probabilistic_df_15
    model_onsets_15[model_name] = onset_da_dict_15

for model_name, model_fp in det_model_paths.items():
        print("=" * 80)
        print(f"Loading data from {model_name}")
        print("=" * 80)
        deterministic_df_15, onset_da_dict_15 = (
            d.compute_metrics_multiple_years(
                years=(
                    model_years[model_name]
                    if model_name in model_years.keys()
                    else model_years["Standard"]
                ),
                imd_folder=config["imd_folder"],
                thres_file=config["thresh_file"],
                model_forecast_dir=model_fp,
                tolerance_days=3,
                verification_window=1,
                forecast_days=15,
                max_forecast_day=15,
                mok=True,
                onset_window=5,
                mok_month=6,
                mok_day=2,
            )
        )

        model_dfs_15[model_name] = deterministic_df_15
        model_onsets_15[model_name] = onset_da_dict_15

Computing climatological onset reference...
Computing climatological onset from 124 years: 1901-2024
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1901.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1901-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1902.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1902-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1903.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1903-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1904.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1904-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1905.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1905-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1906.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1906-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1907.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1907-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1908.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1908-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1909.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1909-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1910.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1910-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1911.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1911-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1912.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1912-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1913.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1913-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1914.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1914-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1915.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1915-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1916.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1916-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1917.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1917-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1918.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1918-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1919.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1919-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1920.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1920-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1921.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1921-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1922.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1922-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1923.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1923-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1924.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1924-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1925.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1925-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1926.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1926-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1927.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1927-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1928.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1928-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1929.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1929-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1930.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1930-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1931.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1931-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1932.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1932-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1933.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1933-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1934.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1934-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1935.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1935-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1936.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1936-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1937.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1937-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1938.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1938-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1939.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1939-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1940.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1940-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1941.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1941-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1942.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1942-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1943.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1943-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1944.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1944-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1945.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1945-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1946.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1946-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1947.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1947-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1948.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1948-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1949.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1949-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1950.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1950-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1951.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1951-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1952.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1952-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1953.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1953-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1954.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1954-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1955.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1955-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1956.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1956-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1957.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1957-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1958.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1958-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1959.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1959-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1960.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1960-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1961.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1961-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1962.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1962-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1963.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1963-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1964.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1964-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1965.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1965-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1966.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1966-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1967.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1967-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1968.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1968-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1969.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1969-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1970.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1970-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1971.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1971-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1972.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1972-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1973.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1973-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1974.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1974-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1975.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1975-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1976.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1976-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1977.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1977-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1978.nc
Renamed dimensions: {'TIME': 'time'}

In [38]:
# 30 Day
metrics_df_clim_30, onset_da_clim_30 = (
        c.compute_climatology_baseline_multiple_years(
            years=model_years["Standard"],
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            tolerance_days=5,
            verification_window=16,
            forecast_days=30,
            max_forecast_day=30,
            mok=True,
            onset_window=5,
            mok_month=6,
            mok_day=2,
        )
    )

spatial_clim_30_day = c.create_spatial_far_mr_mae(
        metrics_df_clim_30, dict.fromkeys(model_years["Standard"], onset_da_clim_30)
    )

model_dfs_30 = {}
model_onsets_30 = {}

for model_name, model_fp in prob_model_paths.items():
    print("=" * 80)
    print(f"Loading data from {model_name}")
    print("=" * 80)
    probabilistic_df_30, onset_da_dict_30 = (
        p.compute_metrics_multiple_years(
            years=(
                model_years[model_name]
                if model_name in model_years.keys()
                else model_years["Standard"]
            ),
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            model_forecast_dir=model_fp,
            tolerance_days=5,
            verification_window=16,
            forecast_days=30,
            max_forecast_day=30,
            mok=True,
            onset_window=5,
            mok_month=6,
            mok_day=2,
        )
    )
    model_dfs_30[model_name] = probabilistic_df_30
    model_onsets_30[model_name] = onset_da_dict_30

for model_name, model_fp in det_model_paths.items():
    print("=" * 80)
    print(f"Loading data from {model_name}")
    print("=" * 80)
    deterministic_df_30, onset_da_dict_30 = (
        d.compute_metrics_multiple_years(
            years=(
                model_years[model_name]
                if model_name in model_years.keys()
                else model_years["Standard"]
            ),
            imd_folder=config["imd_folder"],
            thres_file=config["thresh_file"],
            model_forecast_dir=model_fp,
            tolerance_days=5,
            verification_window=16,
            forecast_days=30,
            max_forecast_day=30,
            mok=True,
            onset_window=5,
            mok_month=6,
            mok_day=2,
        )
    )

    model_dfs_30[model_name] = deterministic_df_30
    model_onsets_30[model_name] = onset_da_dict_30

Computing climatological onset reference...
Computing climatological onset from 124 years: 1901-2024
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1901.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1901-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1902.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1902-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1903.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1903-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1904.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1904-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1905.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1905-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1906.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1906-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1907.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1907-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1908.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1908-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1909.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1909-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1910.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1910-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1911.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1911-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1912.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1912-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1913.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1913-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1914.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1914-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1915.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1915-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1916.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1916-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1917.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1917-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1918.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1918-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1919.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1919-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1920.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1920-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1921.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1921-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1922.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1922-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1923.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1923-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1924.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1924-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1925.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1925-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1926.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1926-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1927.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1927-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1928.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1928-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1929.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1929-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1930.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1930-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1931.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1931-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1932.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1932-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1933.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1933-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1934.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1934-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1935.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1935-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1936.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1936-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1937.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1937-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1938.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1938-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1939.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1939-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1940.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1940-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1941.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1941-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1942.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1942-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1943.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1943-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1944.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1944-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1945.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1945-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1946.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1946-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1947.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1947-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1948.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1948-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1949.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1949-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1950.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1950-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1951.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1951-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1952.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1952-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1953.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1953-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1954.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1954-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1955.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1955-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1956.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1956-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1957.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1957-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1958.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1958-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1959.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1959-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1960.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1960-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1961.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1961-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1962.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1962-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1963.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1963-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1964.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1964-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1965.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1965-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1966.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1966-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1967.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1967-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1968.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1968-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1969.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1969-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1970.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1970-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1971.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1971-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1972.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1972-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1973.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1973-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1974.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1974-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1975.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1975-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1976.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1976-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1977.nc
Renamed dimensions: {'TIME': 'time'}
Using MOK date (June 2nd) (1977-06-02) as start date for onset detection
Loading IMD rainfall from: /Users/charlieeden/Desktop/Spring 2026/ds_clinic/monsoon-bench/../monsoon-benchmark_data/imd_rainfall_data/4p0/1978.nc
Renamed dimensions: {'TIME': 'time'}